### ISSUE TITLE
How to extract holes of polygons 

### ISSUE THREAD

**Issue by mgageo** [r-spatial/sf#1616] opened 2021-03-02 12:33 UTC
I have polygons with multiple exterior rings and there are holes in several rings.
I want to extract the holes, not filling the holes like in https://github.com/r-spatial/sf/issues/609
Marc

> library(sf)
> p1 <- rbind(c(-1,-1), c(1,-1), c(1,1), c(-1,1), c(-1,-1))
> pol1 <- st_polygon(list(p1*2, p1))
> pol2 <- st_polygon(list(p1*3+5, p1*2+5))
> pol3 <- st_polygon(list(p1-5))
> x <- st_sfc(pol1, pol2, pol3)
> plot(x)

**Comment by edzer** [comment] 2021-03-02 12:48
If you'd first fill them, then `st_difference` the original polygon from it, you'd have the holes remaining. Since this is a "I want to do xyz" question and not an issue with this package, I'm closing this.

**Closed by edzer** 2021-03-02 12:48 UTC

**Comment by mgageo** [comment] 2021-03-02 14:22
> library(sf)
> p1 <- rbind(c(-1,-1), c(1,-1), c(1,1), c(-1,1), c(-1,-1))
> pol1 <- st_polygon(list(p1*2, p1))
> pol2 <- st_polygon(list(p1*3+5, p1*2+5))
> pol3 <- st_polygon(list(p1-5))
> x <- st_multipolygon(list(pol1, pol2, pol3))
> plot(x)
> y <- st_multipolygon(lapply(x, function(x) x[1]))
> plot(y, add = FALSE)
> z <- st_difference(y, x)
> plot(z, add = TRUE, col = "blue")

**Comment by mgageo** [comment] 2021-03-02 15:02
But it's not working in this case

> p1 <- st_point(c(1,1))
> p2 <- st_point(c(1,-1))
> p3 <- st_point(c(-1,1))
> p4 <- st_point(c(-1,-1))
> p5 <- st_point(c(4,0))
> sfc <- st_sfc(p1, p2, p3, p4, p5)
> sf <- st_sf(a = 1:5, geom = sfc) %>%
>   st_buffer(1.2) %>%
>   summarize()
> x <- st_geometry(sf)
> plot(x)
> y <- st_multipolygon(lapply(x, function(x) x[1]))
> plot(y, add = FALSE)
> z <- st_difference(y, x)
> plot(z, add = TRUE, col = "blue")

**Comment by JosiahParry** [comment] 2023-01-05 13:28
A different perspective on this question: when extracting coordinates from a polygon with a hole using `st_coordinates()` how can one identify which line under `L1` is a hole rather than a ring? 

Is this indicated anyway already? If not, please consider providing a way to do so via `st_coordinates()` (or other)

**Comment by rsbivand** [comment] 2023-01-05 13:44
You haven't given a reproducible example, but for a multipolygon, L3 indicates the feature, L2 the component SF polygon object, and L1 == 1 is the exterior ring, and any L1 > 1 are interior rings aka holes.
