### ISSUE TITLE
Missing units in some CRS

### ISSUE THREAD

**Issue by latot** [r-spatial/sf#2299] opened 2023-12-19 15:16 UTC
Hi, I'm writing tests, some of them are just planar, so I'm using a custom CRS which GDAL parses right, but then the library ```nngeo``` was complaining about the lack of units, debugging I found the next thing:

```R
a <- sf::st_sfc(crs = 'LOCAL_CS["planar", UNIT["METER",1]]')

#GDAL parses it right
sf::st_crs(a)$units_gdal
[1] "METER"

#This one should be "m"
sf::st_crs(a)$units
NULL
```

Thx!

**Comment by edzer** [comment] 2023-12-19 17:16
```r
> sf::st_crs(a)$ud_unit
1 [m]
```

**Comment by latot** [comment] 2023-12-19 17:35
maybe this comes from this example:

https://github.com/r-spatial/sf/blob/ec39ef436388ce58ef68d104038e2e34e5121d5f/R/crs.R#L396

**Comment by latot** [comment] 2023-12-19 17:39
But this also works for other CRSs:

```R
a <- sf::st_sfc(crs = 32718)
sf::st_crs(a)$units
[1] "m"
```

The ```units``` is used in libs like ```nngeo``` to check the unit type.

**Comment by edzer** [comment] 2023-12-19 18:41
That works for CRSs that have a proj4 representation:
```r
a <- sf::st_sfc(crs = 32718)
st_crs(a) |> st_crs(parameters = TRUE) -> b
b$proj4string
# [1] "+proj=utm +zone=18 +south +datum=WGS84 +units=m +no_defs"
a <- sf::st_sfc(crs = 'LOCAL_CS["planar", UNIT["METER",1]]')
st_crs(a) |> st_crs(parameters = TRUE) -> b
b$proj4string
# [1] NA
```

**Comment by latot** [comment] 2023-12-19 18:52
mmm, that is more complex rn, because proj4 is replaced by WKT2, not all new CRS will have a proj4 representation.

Who extract the unit? GDAL or SF?

**Comment by edzer** [comment] 2023-12-19 18:55
GDAL extracts the proj4string from WKT2. Sf extracts the units from that.

**Comment by edzer** [comment] 2023-12-19 19:51
> In that case, I think the best would be to SF extract the unit directly from WKT2 instead to do from proj4, that will do it works for all CRSs.

SF is not going to interpret WKT2. I would suggest `nngeo` to use `ud_unit`, not `units`, if that is what bothers you

> Is there also other SF features that only works from Proj4string?

All elements of the proj4string can be queried with `$.crs`.

I'd agree that phasing out any use of proj4strings would be an effort worth trying; this involves reverse dependency on all 500+ packages depending on sf, and contacting authors of packages with errors caused by that activity.

**Comment by latot** [comment] 2023-12-19 20:01
I agree with all that, which option, would be the best for long term? there ```ud_unit`` `and ```units_gdal```, or both are good enough?

**Comment by edzer** [comment] 2023-12-19 20:32
https://journal.r-project.org/archive/2016/RJ-2016-061/index.html

**Comment by latot** [comment] 2023-12-19 20:39
Oks, due to the nature of that text, I think you are telling we should works over the libraries that uses units than read things from GDAL.

Thx for the help!

**Comment by latot** [comment] 2023-12-19 20:43
What do you think... of a warning when someone try to read something from proj4? maybe that can helps to stop using it on time, there is too much packages that depends on sf, maybe helps.

**Comment by edzer** [comment] 2023-12-19 20:51
I was thinking of that too, but believe there are too many projections still where the only "easy" way to define them is to use the proj4string. Think of laea with a self-chosen meridian of natural origin - who would define this in WKT2? How would you isolate this meridian from the WKT2? Let's not ban it out before the rest of the world has done so.

**Comment by rsbivand** [comment] 2023-12-20 08:42
And what about:                         message('writing: substituting ENGCRS["Undefined Cartesian SRS with unknown unit"] for missing CRS') in https://github.com/r-spatial/sf/blob/db96e85949b817704a6cd27fc9f3365fb2b13dcd/R/read.R#L548 ? Since we introduced that, we questioned whether we can assume units to be metres for NA crs.

**Comment by edzer** [comment] 2023-12-20 09:29
That does this:
```r
library(sf)
# Linking to GEOS 3.11.1, GDAL 3.6.4, PROJ 9.1.1; sf_use_s2() is TRUE
a <- sf::st_sfc(crs = "ENGCRS[\"Undefined Cartesian SRS with unknown unit\",EDATUM[\"Unknown engineering datum\"],CS[Cartesian,2],AXIS[\"X\",unspecified,ORDER[1],LENGTHUNIT[\"unknown\",0]],AXIS[\"Y\",unspecified,ORDER[2],LENGTHUNIT[\"unknown\",0]]]")
st_crs(a)
# Coordinate Reference System:
#   User input: ENGCRS["Undefined Cartesian SRS with unknown unit",EDATUM["Unknown engineering datum"],CS[Cartesian,2],AXIS["X",unspecified,ORDER[1],LENGTHUNIT["unknown",0]],AXIS["Y",unspecified,ORDER[2],LENGTHUNIT["unknown",0]]] 
#   wkt:
# ENGCRS["Undefined Cartesian SRS with unknown unit",
#     EDATUM["Unknown engineering datum"],
#     CS[Cartesian,2],
#         AXIS["x",unspecified,
#             ORDER[1],
#             LENGTHUNIT["unknown",0]],
#         AXIS["y",unspecified,
#             ORDER[2],
#             LENGTHUNIT["unknown",0]]]
st_crs(a)$ud_unit
# NULL
st_crs(a)$proj4string
# [1] NA
st_crs(a)$units
# NULL
```
the `NULL` value for `$ud_unit` is documented.

**Comment by rsbivand** [comment] 2023-12-20 13:01
@latot There are lots of proj4string representations that do not map to WKT2-2019 at all. People should not use them, but if they choose to because their research needs that framing, and there is no viable alternative in WKT2-2019, then that is their choice. If their work covers large areas, the relative loss of accuracy in not having proper datum support or ways of disambiguating datum ensembles like EPSG:4326 may not matter to them, though it would matter to researchers in say precision agriculture.

**Comment by latot** [comment] 2023-12-20 17:49
uff, that seems a lot complex!

If WKT2 can't eat Proj4Strings, what I imagine would be something like hide/warning every feature that try to reads directly anything from them, likely SF should handle that...

But is hard, if someone do some code wants to retrieve some data that only exists on WKT2 or Proj4String........

Maybe would be better change the focus here, if a property only exists in one, and you try to retrieve it, get an error instead of NULL would be great, would be like "you should not read from here".

If can be retrieved from both, be able to SF handle that and access to it in a uniform way.

**Comment by edzer** [comment] 2023-12-20 20:44
See [here](https://en.wikipedia.org/wiki/PROJ): "The history of PROJ dates back to the late 1970s" ...

**Comment by edzer** [comment] 2023-12-21 18:02
Close the issue?

**Closed** 2024-01-08 10:26 UTC
