### ISSUE TITLE
write_sf/read_sf cycle results in different geometry column names on different backends

### ISSUE THREAD

**Issue by cmcaine** [r-spatial/sf#719] opened 2018-04-21 22:30 UTC
gpkg gives geometry the column name "geom", geojson and shp give "geometry".

I would expect all backends to give the same geometry column name so that e.g. `rbind()` is easier.

Maybe all new backends could standardise on "geometry". I can't think of a good deprecation path off the top of my head if you wanted to change the gpkg writer/reader behaviour.

Slightly related to #282.

**Comment by Robinlovelace** [comment] 2018-04-22 08:01
I've also noticed this and wanted to put in an issue. As a note @cmcaine referring to geometry columns with `st_geometry(x)` is more failsafe than `x$geometry`, as illustrated below which also does some benchmarking for different file formats and for point creation related to #636 - showing data I/O to hd is almost as fast as creating points from a df (as there's no write phase in the 1st tic/toc, just read):

``` r
library(sf)
#> Linking to GEOS 3.5.1, GDAL 2.1.2, proj.4 4.9.3
library(tictoc)
n = 10000
d = data.frame(v1 = 1:n, v2 = rep(letters, n), x = runif(n), y = runif(n))
tic()
x = st_as_sf(d, coords = c("x", "y"))
toc()
#> 3.754 sec elapsed
f = c("x.shp", "x.geojson", "x.gpkg")
for (i in f) {
  tic()
  write_sf(x, i)
  x_new = read_sf(i)
  # x_new$geometry # fails for gpkg
  st_geometry(x_new)
  toc()
}
#> 7.13 sec elapsed
#> 11.639 sec elapsed
#> 12.074 sec elapsed
file.remove(f)
#> [1] TRUE TRUE TRUE
```

<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.4 (2018-03-15)
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  tz       Etc/UTC                     
#>  date     2018-04-22
#> Packages -----------------------------------------------------------------
#>  package     * version    date       source                              
#>  backports     1.1.2      2017-12-13 CRAN (R 3.4.4)                      
#>  base        * 3.4.4      2018-04-21 local                               
#>  class         7.3-14     2015-08-30 CRAN (R 3.4.4)                      
#>  classInt      0.2-3      2018-04-16 CRAN (R 3.4.4)                      
#>  compiler      3.4.4      2018-04-21 local                               
#>  datasets    * 3.4.4      2018-04-21 local                               
#>  DBI           0.8        2018-03-02 CRAN (R 3.4.4)                      
#>  devtools      1.13.5     2018-02-18 CRAN (R 3.4.4)                      
#>  digest        0.6.15     2018-01-28 CRAN (R 3.4.4)                      
#>  e1071         1.6-8      2017-02-02 CRAN (R 3.4.4)                      
#>  evaluate      0.10.1     2017-06-24 CRAN (R 3.4.4)                      
#>  formatR       1.5        2017-04-25 CRAN (R 3.4.4)                      
#>  graphics    * 3.4.4      2018-04-21 local                               
#>  grDevices   * 3.4.4      2018-04-21 local                               
#>  grid          3.4.4      2018-04-21 local                               
#>  htmltools     0.3.6      2017-04-28 CRAN (R 3.4.4)                      
#>  knitr         1.20       2018-02-20 CRAN (R 3.4.4)                      
#>  magrittr      1.5        2014-11-22 CRAN (R 3.4.4)                      
#>  memoise       1.1.0      2017-04-21 CRAN (R 3.4.4)                      
#>  methods     * 3.4.4      2018-04-21 local                               
#>  pillar        1.2.1      2018-02-27 CRAN (R 3.4.4)                      
#>  Rcpp          0.12.16    2018-03-13 CRAN (R 3.4.4)                      
#>  rlang         0.2.0.9001 2018-04-21 Github (r-lib/rlang@82b2727)        
#>  rmarkdown     1.9        2018-03-01 CRAN (R 3.4.4)                      
#>  RPostgreSQL   0.6-2      2017-06-24 CRAN (R 3.4.4)                      
#>  rprojroot     1.3-2      2018-01-03 CRAN (R 3.4.4)                      
#>  sf          * 0.6-2      2018-04-21 Github (r-spatial/sf@b69c835)       
#>  spData        0.2.8.8    2018-04-21 Github (nowosad/spData@8edd206)     
#>  spDataLarge   0.2.6.3    2018-04-21 Github (nowosad/spDataLarge@22c826a)
#>  stats       * 3.4.4      2018-04-21 local                               
#>  stringi       1.1.7      2018-03-12 CRAN (R 3.4.4)                      
#>  stringr       1.3.0      2018-02-19 CRAN (R 3.4.4)                      
#>  tibble        1.4.2      2018-01-22 CRAN (R 3.4.4)                      
#>  tictoc      * 1.0        2014-06-17 CRAN (R 3.4.4)                      
#>  tools         3.4.4      2018-04-21 local                               
#>  udunits2      0.13       2016-11-17 CRAN (R 3.4.4)                      
#>  units         0.5-1      2018-01-08 CRAN (R 3.4.4)                      
#>  utils       * 3.4.4      2018-04-21 local                               
#>  withr         2.1.2      2018-04-21 Github (jimhester/withr@79d7b0d)    
#>  yaml          2.1.18     2018-03-08 CRAN (R 3.4.4)
```

</details>


Interesting that the flawed shapefile still seems to be the fastest, at least for these point on the docker set-up I'm on at the moment.

**Comment by edzer** [comment] 2018-04-22 18:33
@Robinlovelace please start a new issue if you have one, or help with this one here.

@cmcaine : no, we interface gdal, and gdal provides names of geometries for those drivers for which this is meaningful. Even if it is not meaningful for shapefile or geojson, some of the other 91 interfaced vector formats may have meaningful names for geometry columns. Also, files to import, and hence `sf` objects, may have more than one geometry column, in which case giving one of them the name `geometry` would be pointless. Think of database tables (e.g. PostGIS), here geometry columns are named, and we inherit those names in R, so that we can make a clean roundtrip.

**Comment by Robinlovelace** [comment] 2018-04-22 20:54
Sure, was trying to help by suggesting `st_geometry()` as a failsafe way and providing code that illustrated the issue - the benchmarking being an afterthought. I think the fact that common open source formats seem to be slower than shapefiles is an issue, but am not sure it merits opening an issue. Cheers for the explanation in any case, sounds like the answer is 'wontfix' or rather 'not broke in the first place'!

**Comment by cmcaine** [comment] 2018-04-23 01:43
@Robinlovelace I've found st_geometry, but it doesn't really help for my use case. Thanks for mentioning it, though.

@edzer Cool, so sounds like the bug is in gdal for choosing different arbitrary names for geometry in formats for which there is not a meaningful name?

Are there any non-db backends that support multiple geometry columns?

**Comment by edzer** [comment] 2018-04-23 06:02
If gdal does not provide a geometry name, `sf` sets it to `geometry`; I see no bug in gdal in this respect.

**Closed** 2018-04-23 06:43 UTC

**Comment by Robinlovelace** [comment] 2018-04-23 08:36
@cmcaine in case it helps see the reprex below which allows you to `rbind` two `sf` objects with different geometries. Would be interested to see other solutions:

library(sf)
#> Linking to GEOS 3.5.1, GDAL 2.2.2, proj.4 4.9.2
d = data.frame(v1 = 1:3, x = 1:3, y = 1:3)
x1 = st_as_sf(d, coords = c("x", "y"))
write_sf(x1, "/tmp/x.gpkg")
x2 = read_sf("/tmp/x.gpkg")
rbind(x, x2)  # fail
#> Error in rbind(x, x2): object 'x' not found
x2 = st_sf(st_set_geometry(x2, NULL), geometry = st_geometry(x2))
rbind(x1, x2)
#> Simple feature collection with 6 features and 1 field
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 1 xmax: 3 ymax: 3
#> epsg (SRID):    NA
#> proj4string:    NA
#>   v1    geometry
#> 1  1 POINT (1 1)
#> 2  2 POINT (2 2)
#> 3  3 POINT (3 3)
#> 4  1 POINT (1 1)
#> 5  2 POINT (2 2)
#> 6  3 POINT (3 3)

**Comment by bholtdwyer** [comment] 2023-03-08 06:19
Having just had some code fail in a hard-to-detect way because the name of a column was "geometry" when a sf object was saved, but "geom" when it was loaded from the .gpkg file, I'm with @cmcaine on this. It would be easy to modify read_sf to always give the geometry column the name "geometry" (in fact I'm about to write my own wrapper function to make sure I can't make this mistake again!)

**Comment by ailich** [comment] 2024-04-18 20:18
I agree that calling the column "geometry" if it is not named, and not renaming due to the potential for multiple geometries and for allowing for a "clean round trip" through R is good practice even if it may involve renaming in some cases to join multiple files. However, I think it'd also be beneficial to prevent renaming the geometry column when writing to file. This is currently not the case for geopackage files. For example if "nc.shp" is read in as an sf object, the geometry column is named "geometry", but if that object is written to a "gpkg" file and read it back in, the geometry column is named "geom".

``` r
library(sf)
#> Linking to GEOS 3.11.2, GDAL 3.6.2, PROJ 9.2.0; sf_use_s2() is TRUE

nc <- st_read(system.file("shape/nc.shp", package="sf"))

st_write(nc, "output.gpkg", append=FALSE)

nc2<- st_read("output.gpkg")

names(nc)[15]
#> [1] "geometry"
names(nc2)[15]
#> [1] "geom"
```

<sup>Created on 2024-04-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by edzer** [comment] 2024-04-18 20:35
> ... the geometry column is named "geom".

I don't think that is caused by `sf`.

**Comment by ailich** [comment] 2024-04-18 20:44
Yeah, I'm not sure about the cause. I tried setting the GDAL option using `st_write(nc, "output.gpkg", driver = "GPKG", layer_options = "LAUNDER=NO")` to prevent column renaming but get "GDAL Message 6: dataset output.gpkg does not support layer creation option LAUNDER". So maybe it's a GDAL or geopackage thing. It can cause a few hiccups here and there but not a big deal especially if this is a not an `sf` thing and it'd be hard to track down.

**Comment by cmcaine** [comment] 2024-04-18 20:55
As I noted in 2018, the geometry column name is set by the GDAL gpkg driver when you load a gpkg file. Same for mysql and maybe some other formats.

**Comment by cmcaine** [comment] 2024-04-18 22:10
Quoting @edzer from 2018:

>  Think of database tables (e.g. PostGIS), here geometry columns are named, and we inherit those names in R, so that we can make a clean roundtrip.

If we give the GEOMETRY_NAME option to the GDAL/gpkg driver then we can specify the geometry column name to match whatever the dataframe's column name is: `paste0("GEOMETRY_NAME=", df$sf_column)`

This looks like it will allow round-tripping data from an SFC in R with a geometry column named "geometry" to a GPKG on disk and then back into R, which would solve this issue for me.

I don't use R much any more, please excuse me if my sample code doesn't make sense.
