### ISSUE TITLE
Polygons and polylines do not display in Leaflet

### ISSUE THREAD

**Issue by rubenpeters91** [r-spatial/sf#880] opened 2018-11-01 10:32 UTC
When I read a shape file containing polygons or polylines using 0.7-1 or 0.7-0 of sf and the newest version of leaflet (2.0.2) the polygons or lines are not displayed in a leaflet plot, however they are displayed when I'm using plot() or tmap().

Rolling back to version 0.6-3 fixes the issue.

For example:
```
library(sf)
library(tmap)

#A random example, this will work for any shapefile that I've tried
#http://geoportaal-s-hertogenbosch.opendata.arcgis.com/datasets/a08bb84043a74b91b1243c50e104f337_1.zip
shape <- st_read("Wijken.shp")

tmap_mode("plot")
tm_shape(shape) + tm_polygons() #This will plot the polygons

tmap_mode("view")
tm_shape(shape) + tm_polygons() #This will not

```

**Comment by tim-salabim** [comment] 2018-11-02 08:21
I am not sure this is really an sf issue. The problem is that leaflet (or better javascript in general) doesn't like named objects very much. Reading a shapefile, however, leads to a named `sfc_*` column. [In mapview](https://github.com/r-spatial/mapview/blob/develop/R/sf.R#L151) we therefore make sure to set names of geometries to `NULL`. Hence, everything works as expected with `mapview(shape)`.
leaflet does not do this, and apparently neither does tmap. 

Whether this should be addressed in sf, leaflet or tmap warrants pinging @schloerke, @jcheng5 and @mtennekes to discuss where this should be addressed.

For now what you need to do is
```r
names(st_geometry(shape)) = NULL
```
then 
```r
tmap_mode("plot")
tm_shape(shape) + tm_polygons()
```
will work as expected.

**Comment by mtennekes** [comment] 2018-11-02 08:33
It has already been fixed in `tmap` (see https://github.com/mtennekes/tmap/issues/248), so it should work with the github version.

**Comment by tim-salabim** [comment] 2018-11-02 08:46
This may also be of interest for @SymbolixAU regarding [spatialwidget](https://github.com/SymbolixAU/spatialwidget)

**Comment by SymbolixAU** [comment] 2018-11-05 02:06
@tim-salabim 

>  (or better javascript in general) doesn't like named objects very much

I'm not too clear on what you mean here; do you have an example of a 'named' object in javascript which causes this issue?

**Closed** 2018-11-16 11:34 UTC
