### ISSUE TITLE
st_read for geojson input errors during file.exists check

### ISSUE THREAD

**Issue by tarakc02** [r-spatial/sf#2112] opened 2023-03-06 19:38 UTC
**Describe the bug**

When I run `sf::read_sf(x)` and x is a `geojson` object (as returned by `geojsonio::as.json`), I sometimes get the following error:

```
  Error in `file.exists(dsn)`: file name conversion problem -- name too long?
  Backtrace:
      ▆
   1. ├─rmapzen::as_sf(ca_tiles$roads) at test-as-sf.R:17:4
   2. └─rmapzen:::as_sf.mapzen_vector_layer(ca_tiles$roads)
   3.   └─sf::read_sf(as_json(geo))
   4.     ├─sf::st_read(...)
   5.     └─sf:::st_read.default(...)
   6.       └─sf:::st_read.character(dsn, layer, ...)
   7.         └─base::file.exists(dsn)
```

`dsn` is not a file (it's a character string of json), and I'm assuming the call would work if `dsn` weren't flagged as an invalid path. I only see the error on Windows Server 2022 + R-devel (encountered when submitting to win-builder before updating a package on CRAN), and I can not reproduce the error on any of the test environments I have available to work on.

**To Reproduce**

See note above, this works fine on Mac and Ubuntu using R-release, but not on Windows Server 2022 with R-devel, according to CRAN's automated servers as well as winbuilder.

```R
library(rmapzen)
as_sf(ca_tiles$roads)
```

**Additional context**

I only see the error on Windows Server 2022 + R-devel (encountered when submitting to win-builder before updating a package on CRAN), and I can not reproduce the error on any of the test environments I have available to work on.

I apologize that I cannot run `sessionInfo` on the machine where this test fails...

**Comment by edzer** [comment] 2023-03-09 10:18
If we would know on how long a file name must be on Windows before it triggers an error in `file.exists()` then it would be trivial to work around this for Windows.

**Comment by kadyb** [comment] 2023-03-09 10:57
259 characters? Yesterday Tomas Kalibera wrote blogpost about it (https://blog.r-project.org/2023/03/07/path-length-limit-on-windows/). This should also be improved in R devel for Windows 10 and 11.

**Comment by edzer** [comment] 2023-03-09 12:55
Very timely! @kalibera, I think this is related to your research: should `base::file.exists()` ever result in an error, as reported above?

**Comment by kalibera** [comment] 2023-03-09 17:57
Thanks, I can reproduce using

```
file.exists(paste(readLines("ca-tiles.json"), collapse = "\n"))
```
with the json file downloaded from the gist. 

You were right, the problem is the length of the path name (over 3M characters), the string is otherwise valid. Implausibly long path names are documented to silently result in `FALSE` in `file.exists`, so the current R-devel behavior is a bug which I've introduced while working on the long path support.

Fixed now (so that false is returned again). Thanks for the report.

You may have to wait a day or so for winbuilder to pick up the latest version. The OS version doesn't matter in this case, it was only about the version of R-devel used for the checking.

While the behavior for implausibly long paths is documented, I would rather not rely on that arbitrary strings would silently be treated as non-existent, even if they were validly encoded. E.g. you might, well in theory, but still, run into an existing file name by accident, etc.

**Closed** 2023-03-10 21:02 UTC
