### ISSUE TITLE
Problem in setting or changing change CRS in R

### ISSUE THREAD

**Issue by tolga-metu** [r-spatial/sf#2302] opened 2023-12-26 14:45 UTC
I posted this earlier today at [stackoverflow](https://stackoverflow.com/questions/77716942/problem-in-setting-or-changing-change-crs-in-r)

I use the sf package for setting or changing the CRS (R version 4.2). For some other project, I had to update to the new version of the R (v4.3).

However, now I need to change the CRS of an object and I receive the following error:

```
In CPL_crs_from_input(x) :
  GDAL Error 1: PROJ: proj_create_from_database: Cannot find proj.db
```

I tried it on another PC and it is working. So, the R version or packages are not an issue here. 
I made a clean install and re-installed my previous packages (sf, raster, sp, and dependencies). Also, tried to set proj.db environment

`Sys.setenv(PROJ_LIB = "...\\AppData\\Local\\R\\win-library\\4.3\\sf\\proj")`

I also tried going back to v4.2 But still, I am getting the same error. I am using the most basic commands and it is not working.

```
df <- CRS(SRS_string = "EPSG:4326")
df <- st_crs(4326)
```
I need a fix to this problem without formatting the PC.

**Comment by rsbivand** [comment] 2023-12-26 15:12
Do not cross-post, either SO or here, to prevent any duplication of effort. You do not give your OS or versions of packages - add the complete output of `sessionInfo()`, both for the PC on which the connections between `sf` and `proj.db` work, and do not work.

Is `PROJ_LIB` set by any other software on your non-working PC? Since you seem to use Windows, did you install the binary package of `sf`, or try to install from source?

**Comment by rsbivand** [comment] 2023-12-26 16:15
Probably a duplicate of https://github.com/r-spatial/sf/issues/2298 on the failing PC. If so, use `Sys.setenv("PROJ_LIB"="")` before loading `sf`, as in https://github.com/r-spatial/sf/issues/2298#issuecomment-1864805440.

**Closed** 2023-12-26 20:21 UTC

**Comment by tolga-metu** [comment] 2023-12-26 20:24
Using `Sys.setenv("PROJ_LIB"="")` solved my problem. Thanks for your help. I will add the sessionInfo if the error reproduces.

**Comment by tolga-metu** [comment] 2023-12-27 10:26
This is the session info without using `Sys.setenv("PROJ_LIB"="")`

```
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=Turkish_Turkey.utf8  LC_CTYPE=Turkish_Turkey.utf8    LC_MONETARY=Turkish_Turkey.utf8
[4] LC_NUMERIC=C                    LC_TIME=Turkish_Turkey.utf8    

time zone: Europe/Istanbul
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] readxl_1.4.3    tmap_3.3-4      sf_1.0-15       lubridate_1.9.3 forcats_1.0.0   stringr_1.5.1   dplyr_1.1.4    
 [8] purrr_1.0.2     readr_2.1.4     tidyr_1.3.0     tibble_3.2.1    ggplot2_3.4.4   tidyverse_2.0.0

loaded via a namespace (and not attached):
 [1] gtable_0.3.4       raster_3.6-26      htmlwidgets_1.6.4  rJava_1.0-10       lattice_0.21-9     tzdb_0.4.0        
 [7] vctrs_0.6.5        tools_4.3.2        crosstalk_1.2.1    generics_0.1.3     parallel_4.3.2     proxy_0.4-27      
[13] fansi_1.0.6        pkgconfig_2.0.3    KernSmooth_2.23-22 RColorBrewer_1.1-3 leaflet_2.2.1      lifecycle_1.0.4   
[19] compiler_4.3.2     munsell_0.5.0      terra_1.7-65       codetools_0.2-19   leafsync_0.1.0     stars_0.6-4       
[25] htmltools_0.5.7    class_7.3-22       pillar_1.9.0       classInt_0.4-10    lwgeom_0.2-13      wk_0.9.1          
[31] abind_1.4-5        tidyselect_1.2.0   digest_0.6.33      stringi_1.8.3      fastmap_1.1.1      grid_4.3.2        
[37] colorspace_2.1-0   cli_3.6.2          magrittr_2.0.3     xlsxjars_0.6.1     base64enc_0.1-3    dichromat_2.0-0.1 
[43] XML_3.99-0.16      utf8_1.2.4         leafem_0.2.3       e1071_1.7-14       withr_2.5.2        scales_1.3.0      
[49] sp_2.1-2           timechange_0.2.0   cellranger_1.1.0   png_0.1-8          hms_1.1.3          tmaptools_3.1-1   
[55] viridisLite_0.4.2  s2_1.1.6           rlang_1.1.2        Rcpp_1.0.11        glue_1.6.2         DBI_1.2.0         
[61] xlsx_0.6.5         rstudioapi_0.15.0  R6_2.5.1           units_0.8-5       
```
I can't share the session info for the other PC because it is running a script. But it has the same R version, the same platform (x86_64-w64-mingw32/x64 (64-bit), and Windows 10 x64 (build 19045). I installed sf package on both machines yesterday.

> Is PROJ_LIB set by any other software on your non-working PC? 

QGIS is probably sharing PROJ_LIB. Also, I updated the proj package using OSGEO4W to fix this error yesterday but it did not work. However, I have been working with both of them for over a year without any problems and the only change was the R update.

> Since you seem to use Windows, did you install the binary package of sf, or try to install from source?

I used the `install.packages("sf")` command using RStudio for both machines.
 
I used the console to update R from RGUI `updateR()` and copied packages to the new version, which might be the main cause of this problem.

**Comment by rsbivand** [comment] 2023-12-27 13:58
Probably QGIS and/or OSGEO4W have the environment variable set. If `PROJ_LIB` is set to the empty string before `sf` is loaded, both `PROJ` and `GDAL` are given the correct path to `proj.db` in 1.0-15; if not, `PROJ` may get the correct path but `GDAL` will not, and may try the one given by `PROJ_LIB`. 

In general, doing anything relating to updating or package management from the Rstudio IDEmay lead to further ambiguity. In any future issues, always use Rgui (as you did here in part) or R at a Windows console/terminal. This reduces the count of components in play for which version collisions may need consideration.

**Comment by edzer** [comment] 2023-12-27 14:46
Probably duplicate of #2298
