### ISSUE TITLE
Problem on Arch Linux

### ISSUE THREAD

**Issue by ismailsunni** [r-spatial/sf#1238] opened 2020-01-10 11:08 UTC
I tried to run the code from the [SDSR book](https://github.com/edzer/sdsr) inside several operating systems. Interestingly, I found a problem that only occurs on Arch Linux.

Here is the code:
```R
library(sf)
library(rnaturalearth)
w <- ne_countries(scale = "medium", returnclass = "sf")
layout(matrix(1:2, 1, 2), c(2,1))
plot(st_geometry(w))

circ = function(l = c(-180:180), lon0 = 0, lat0 = 30) {
	deg2rad = pi / 180
	lat = atan(-cos((l - lon0) * deg2rad)/tan(lat0 * deg2rad)) / deg2rad
	xy = if (lat0 == 0) {
		l1 = lon0 - 90
		l2 = lon0 + 90
		rbind(c(l1,-90), c(l2,-90), c(l2,0), c(l2,90), c(l1,90), c(l1,0), c(l1,-90))
	} else if (lat0 > 0) {
		xy = cbind(lon = l, lat = lat)
		rbind(c(-180,90),xy,c(180,90),c(-180,90))
	} else {
		xy = cbind(lon = l, lat = lat)[length(l):1,]
		rbind(c(180,-90), xy, c(-180,-90),c(180,-90))
	}
	st_sfc(st_polygon(list(xy)), crs = st_crs(4326))
	# TODO: break at dateline, guarantee within -180,180
}

m = st_make_grid()
m = st_segmentize(m, 4e5)

i = 0
par(mar = rep(0,4))
lat=30+(i/2)
lon=-10-(i/2)
p4s=paste0("+proj=ortho +lat_0=", lat, " +lon_0=", lon)
plot(st_transform(m, st_crs(p4s), check = TRUE), col = 'lightblue', border = 'grey')
crc = circ(lat0 = lat, lon0 = lon)
w0 = suppressWarnings(st_intersection(w, crc))
w0 = st_cast(w0, "MULTIPOLYGON")
plot(st_transform(st_geometry(w0), st_crs(p4s), check = TRUE), add = TRUE)
```
The error message is:
```bash
Error in geos_op2_geom("intersection", x, y) : 
  st_crs(x) == st_crs(y) is not TRUE
```

To replicate, you can run this:
```bash
docker run  -it --rm ismailsunni/gnur-3.6.1-archlinux-geospatial
```
Then run the code above.
The docker file is [here](https://github.com/ismailsunni/dockeRs/blob/master/gnuR-3.6.1-archlinux-geospatial/Dockerfile) that extend the docker file [here](https://github.com/ismailsunni/dockeRs/blob/master/gnuR-3.6.1-archlinux/Dockerfile)

It works fine on Debian, Ubuntu, and Fedora. I have a working Debian and Fedora docker image if you need to test.

```bash
docker run  -it --rm ismailsunni/gnur-3.6.1-debian-geospatial R
```

and 
```bash
docker run  -it --rm ismailsunni/gnur-3.6.1-fedora-geospatial R
```

Thanks!

Related issue: https://github.com/ismailsunni/dockeRs/issues/40

**Comment by edzer** [comment] 2020-01-10 12:48
Thanks, @ismailsunni , for making this so easily reproducible. I find the same error under current ubuntu LTS with ubuntugis-unstable spatial libs, which also has
```r
> library(sf)
Linking to GEOS 3.8.0, GDAL 3.0.2, PROJ 6.2.1
```
The problem is that current GDAL / PROJ does not consider these to equivalent:
```
> st_crs(w)
Coordinate Reference System:
  EPSG: 4326 
  proj4string: "+proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs"
> st_crs(crc)
Coordinate Reference System:
  EPSG: 4326 
  proj4string: "+proj=longlat +datum=WGS84 +no_defs"
```
which I'd hoped it would. I'll patch the book code and then close it here.

**Comment by rsbivand** [comment] 2020-01-10 12:49
Show what `sf_extSoftVersion()` reports on all versions. Almost certainly, the versions of PROJ and GDAL differ between platforms.

**Closed** 2020-01-10 13:39 UTC

**Comment by ismailsunni** [comment] 2020-01-10 17:02
Thanks for the explanation. It seems because the GDAL and PROJ versions.
My Debian
```R
> sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.5.1"        "2.1.2"        "4.9.3"         "true"        "false" 
```

My Fedora
```R
> sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.7.1"        "2.3.2"        "6.2.0"         "true"         "true" 
```

My Arch Linux
```R
> sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.8.0"        "3.0.2"        "6.2.1"         "true"         "true" 

```
