### ISSUE TITLE
Unable to install SF on Fedora 32

### ISSUE THREAD

**Issue by notagoodidea** [r-spatial/sf#1379] opened 2020-04-20 15:00 UTC
Hi,

I am trying to install `sf` on Fedora 32, all system are updated to the latest version of the repos.
For the dependencies : `proj-epsg` and `proj-nad` are not available in the repos.

Trying to install `sf` in RStudio with `install.packages("sf")` give me the following output : 

> configure: CC: gcc -m64
> configure: CXX: g++ -m64 -std=gnu++11
> checking for gdal-config... /usr/bin/gdal-config
> checking gdal-config usability... yes
> configure: GDAL: 3.0.4
> checking GDAL version >= 2.0.1... yes
> checking for gcc... gcc -m64
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc -m64 accepts -g... yes
> checking for gcc -m64 option to accept ISO C89... none needed
> checking how to run the C preprocessor... gcc -m64 -E
> checking for grep that handles long lines and -e... /usr/bin/grep
> checking for egrep... /usr/bin/grep -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking gdal.h usability... yes
> checking gdal.h presence... yes
> checking for gdal.h... yes
> checking GDAL: linking with --libs only... yes
> checking GDAL: /usr/share/gdal/pcs.csv readable... no
> checking GDAL: checking whether PROJ is available for linking:... no
> /usr/bin/ld: /tmp/ccslR7kQ.o: relocation R_X86_64_32 against symbol `__gxx_personality_v0@@CXXABI_1.3` can not be used when making a PIE object; recompile with -fPIE
> collect2: error: ld returned 1 exit status
> configure: Install failure: compilation and/or linkage problems.
> configure: error: cannot link projection code
> ERROR: configuration failed for package ‘sf’
> * removing ‘/home/elie/R/x86_64-redhat-linux-gnu-library/3.6/sf’
> Warning in install.packages :
>   installation of package ‘sf’ had non-zero exit status
> 
> The downloaded source packages are in
> 	‘/tmp/RtmpjecTt8/downloaded_packages’
> Warning message:
> In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
>   there is no package called ‘sf’
> 

rgdal used in another package is perfectly working. 

- System : **Fedora 32 Beta**
- R version : **3.6.3**
- RStudio version : **1.2.5033**
- Problem : **Unable to install *sf* due to linking problem**

Do you need any other informations about that issue?

**Comment by rsbivand** [comment] 2020-04-20 15:08
Duplicate of https://github.com/r-spatial/sf/issues/1369 I think. Do look
first, please.

Roger Bivand
Falsensvei 32
5063 Bergen

man. 20. apr. 2020, 17:01 skrev notagoodidea <notifications@github.com>:

**Closed** 2020-07-08 11:12 UTC
