### ISSUE TITLE
Converting "raw" text from Vertica into geometry

### ISSUE THREAD

**Issue by benjaminrobinson** [r-spatial/sf#1619] opened 2021-03-03 00:07 UTC
I am attempting to pull data from tables in my company's Vertica server that have geometry fields in them into R. There are ways to convert those fields into geometries using a combination of Vertica's `ST_ASTEXT` function and then converting that field into a geometry using `sf`'s `st_as_sfc` function. However, if I pull a table with a geometry field into R without using `ST_ASTEXT` into R the geometry field enters R as a `blob` object.  The blob represents a "raw" vector which represents a list of values.  These values can be converted from raw to hex using the `rawToHex` function in `sf`, for example. Seeing these raw values made it seem to me that I could convert this data to a geometry field using `st_as_sfc` as referenced above.

However, when I do try to use `st_as_sfc` to read these 'raw' blob fields into geometries, I get the following error:
``` r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(odbc)

**QUERY TO GET DATA FROM VERTICA INTO R** -> tmp

st_as_sfc(tmp$geom, EWKB = TRUE, spatialite = FALSE, forceMulti = FALSE)
#> type is 46
#> Error in CPL_read_wkb(x, EWKB, spatialite): reading this sf type is not supported, please file an issue

st_as_sfc(tmp$geom, EWKB = FALSE, spatialite = FALSE, forceMulti = FALSE)
#> wkbType: 1178652718
#> Error in CPL_read_wkb(x, EWKB, spatialite): unsupported wkbType dim in switch
```

<sup>Created on 2021-03-02 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Thus, because of the error message I received, I'm filing this issue.  Like I said, I have a way to get data from Vertica into R and preserve geometries but it doesn't lend itself to functionality that I would love to build so that internal users could convert these "raw" blobs/vectors into geometries more easily.  Thank you for this amazing package!  I greatly appreciate any and all time you dedicate to understanding my issues and hope you can help me resolve them.

- Ben.

**Comment by edzer** [comment] 2021-03-03 08:24
Did you use `ST_AsBinary` before exporting the geometry?

**Comment by benjaminrobinson** [comment] 2021-03-03 22:13
I did not.  I just pulled directly from the Vertica table. Just did another query where I used `ST_AsBinary` to pull the data into R and the `blob` object was different than the `blob` object from the geom object that was pulled in. I'm all types of confused!

**Comment by edzer** [comment] 2021-03-04 08:31
Did it work?

**Comment by benjaminrobinson** [comment] 2021-03-05 17:36
It did not.

**Comment by etiennebr** [comment] 2021-03-11 15:03
@benjaminrobinson, I think a reproducible example would help. Since we can't access your database, try to provide as much details as possible to help us reproduce and understand the issue. 

You can start small:
``` r
st_read(con_odbc, "SELECT st_point(0,0)")
```
Does that work?

Could you share an example of failing `tmp$geom`? 
``` r
sf:::st_as_sfc.WKB("010100000000000000000000000000000000000000", EWKB = TRUE)
#> Geometry set for 1 feature 
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: 0 ymin: 0 xmax: 0 ymax: 0
#> CRS:           NA
#> POINT (0 0)
```

**Comment by benjaminrobinson** [comment] 2021-03-11 15:12
Will get back to you soon with as much info as I can provide!

**Comment by benjaminrobinson** [comment] 2021-03-11 15:23
Here you go!  Hope this has what you're looking for.  I used the Vertica function `STV_GeometryPoint` to replicate `ST_Point`, which I'm guessing is a PostGIS function.

https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/SQLReferenceManual/Functions/Geospatial/STV_GeometryPoint.htm

``` r
library(odbc)
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

## REMOVED ODBC CONNECTION DETAILS

tmp <- dbGetQuery(con, "SELECT STV_GeometryPoint(0,0) AS geom")

str(tmp)
#> 'data.frame':    1 obs. of  1 variable:
#>  $ geom: blob [1:1] 
#>   ..$ : raw  30 00 00 00 ...
#>   ..@ ptype: raw

glimpse(tmp)
#> Rows: 1
#> Columns: 1
#> $ geom <blob> [<30, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00,...

tmp$geom
#> <blob[1]>
#> [1] blob[85 B]

st_as_sfc(tmp$geom, EWKB = TRUE, spatialite = FALSE)
#> type is 0
#> Error in CPL_read_wkb(x, EWKB, spatialite): reading this sf type is not supported, please file an issue
```

<sup>Created on 2021-03-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by etiennebr** [comment] 2021-03-11 16:47
Thanks. Could you share the result of `dput(tmp)`?

**Comment by benjaminrobinson** [comment] 2021-03-11 16:49
Sure!
``` r
dput(tmp)
#> structure(list(geom = structure(list(as.raw(c(0x30, 0x00, 0x00, 
#> 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
#> 0x00, 0x00, 0x15, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
#> 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
#> 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
#> 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xc5, 0xa0, 
#> 0x0f, 0x0e, 0xd0, 0xc0, 0x0b, 0x0a, 0x01, 0x01, 0x00, 0x00, 0x00, 
#> 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
#> 0x00, 0x00, 0x00, 0x00, 0x00))), ptype = raw(0), class = c("blob", 
#> "vctrs_list_of", "vctrs_vctr", "list"))), class = "data.frame", row.names = c(NA, 
#> -1L))
```

<sup>Created on 2021-03-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by etiennebr** [comment] 2021-03-11 17:49
Hmmm... That's not WKB. Could you try `tmp <- dbGetQuery(con, "SELECT ST_GeometryPoint(0,0) AS geom")`? From what I understand in [the documentation](https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/SQLReferenceManual/Functions/Geospatial/GeospatialFunctions.htm), the `ST_` functions are OGC compliant. 

Maybe `st_read(con, query = "SELECT st_asbinary(STV_GeometryPoint(0,0)) AS geom")` would work?

**Comment by etiennebr** [comment] 2021-03-18 00:30
I'm going to close the issue, but feel free to reopen if you think we can help find a solution.

**Closed by etiennebr** 2021-03-18 00:30 UTC
Labels: reprex

**Comment by benjaminrobinson** [comment] 2023-02-01 20:46
My apologies for not looking into this issue for almost 2 years, @etiennebr.  It's come back to my attention.

Running `tmp <- dbGetQuery(con, "SELECT ST_GeographyFromText('POINT(0 0)') AS geom")` produces the normal `blob` object I'd been getting.  However, running `st_read(con, query = "SELECT st_asbinary(STV_GeometryPoint(0,0)) AS geom")` does produce a `Simple feature collection with 1 feature and 0 fields`.  Do you know how I would go about transforming the `blob` object that `dbGetQuery` produces (similar to what you see above that you mentioned was not WKB) into a simple feature?

**Comment by etiennebr** [comment] 2023-02-05 14:34
Hi Ben, unfortunately, I don't see any simple solution to read Vertica's blob. You would need to find or implement a custom reader because it does not seem to be compatible with OGR, which is what `sf` uses.

**Comment by edzer** [comment] 2023-02-05 14:50
If Vertica has it's own custom way representing geometries in binary then you'd have to customize `src/wkb.cpp` - you'll see examples there that read spatialite and GPKG blobs directly, which could be a start. You'd need to have a description of what Vertica does exactly; Vertica may (should) have functions to export standards (OGC) compliant WKB.
