### ISSUE TITLE
Segmentation fault when using st_intersect with EMPTY point geometries

### ISSUE THREAD

**Issue by aaronkirkman** [r-spatial/sf#1009] opened 2019-03-14 14:30 UTC
When `st_intersect` is called with an object with EMPTY point geometries, it triggers a segmentation fault. The code below uses a common beginner's error (switching latitude and longitude), which results in an EMPTY point geometry in the `point_trans` object, to trigger the bug.

```
library(dplyr)
library(magrittr)
library(sf)
library(USAboundaries)

map <- us_states(resolution = "high", states = c("CA", "OR", "WA", "NV", "ID"))

#' Note that the latitude and longitude are switched here as a 
#' convenient way to introduce the bug. Since the latitude is less
#' than -90, the points_trans object below will be empty. This
#' triggers the segmentation fault.
points <- data.frame(
  "lon" = c(41.245696, 38.573965, 44.235577),
  "lat" = c(-118.484406, -121.264677, -115.873234)
)
points_sf <- do.call("st_sfc", c(lapply(1:nrow(points), function(i) {
  st_point(as.numeric(points[i, c("lon", "lat")]))
}), list("crs" = 4326)))

points_trans <- st_transform(points_sf, 2163)
map_trans <- st_transform(map, 2163)

points$state <- apply(st_intersects(map_trans, points_trans, sparse = FALSE), 2,
                      function(col) {
                        map_trans[which(col), ]$state_name
                      })

```

R version 3.5.2
sf version 0.7-3

**Comment by edzer** [comment] 2019-03-14 15:58
I'm seeing
```r
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> library(magrittr)
> library(sf)
Linking to GEOS 3.7.0, GDAL 2.3.2, PROJ 5.2.0
> library(USAboundaries)
> 
> map <- us_states(resolution = "high", states = c("CA", "OR", "WA", "NV", "ID"))
> 
> #' Note that the latitude and longitude are switched here as a 
> #' convenient way to introduce the bug. Since the latitude is less
> #' than -90, the points_trans object below will be empty. This
> #' triggers the segmentation fault.
> points <- data.frame(
+   "lon" = c(41.245696, 38.573965, 44.235577),
+   "lat" = c(-118.484406, -121.264677, -115.873234)
+ )
> points_sf <- do.call("st_sfc", c(lapply(1:nrow(points), function(i) {
+   st_point(as.numeric(points[i, c("lon", "lat")]))
+ }), list("crs" = 4326)))
> 
> points_trans <- st_transform(points_sf, 2163)
> map_trans <- st_transform(map, 2163)
> 
> points$state <- apply(st_intersects(map_trans, points_trans, sparse = FALSE), 2,
+                       function(col) {
+                         map_trans[which(col), ]$state_name
+                       })
Error in `$<-.data.frame`(`*tmp*`, state, value = character(0)) : 
  replacement has 0 rows, data has 3
```
with
<details>

```r
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] USAboundaries_0.3.1 sf_0.7-3            magrittr_1.5       
[4] dplyr_0.8.0.1      

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0              class_7.3-14            crayon_1.3.4           
 [4] assertthat_0.2.0        USAboundariesData_0.3.1 grid_3.5.2             
 [7] R6_2.4.0                DBI_1.0.0               units_0.6-3            
[10] e1071_1.7-0.1           pillar_1.3.0.9001       rlang_0.3.0.9000       
[13] tools_3.5.2             glue_1.3.0              purrr_0.2.5.9000       
[16] compiler_3.5.2          pkgconfig_2.0.2         classInt_0.3-1         
[19] tidyselect_0.2.5        tibble_2.0.0           

```

</details>

**Comment by aaronkirkman** [comment] 2019-03-14 18:11
When I load the sf package, I get `Linking to GEOS 3.5.1, GDAL 2.1.2, PROJ 4.9.3`, so maybe the issue is the libraries on my system (Debian stable) are out of date.

**Comment by edzer** [comment] 2019-03-14 19:42
Is it possible that for one or more of these libraries you have more than one version installed?

**Comment by aaronkirkman** [comment] 2019-03-29 19:50
I haven't installed more than one version of these libraries _intentionally_, but it's certainly possible that I installed multiple versions accidentally. I'll do some digging.

**Comment by edzer** [comment] 2019-04-07 20:13
I'm closing this because of a lacking ability to reproduce this.

**Closed by edzer** 2019-04-07 20:13 UTC
