### ISSUE TITLE
PROJ and sqlite3 are available for linking:... no

### ISSUE THREAD

**Issue by gdk43** [r-spatial/sf#1268] opened 2020-02-14 02:25 UTC
Hello,
First of all, my system is Centos 7.6 OS.

My goal was installing the monocle3, 
but always failed to here that installing the "sf".

here is my code 

remotes::install_github('r-spatial/sf', configure.args=
('--with-gdal-config=/usr/local/bin/gdal-config 
--with-proj-lib=/usr/local/lib
--with-proj-include=/usr/local/include
--with-proj-share=/usr/local/share/proj 
--with-proj-data=/usr/local/share/proj
--with-geos-config=/usr/local/bin/geos-config'))

![image](https://user-images.githubusercontent.com/59091518/74496195-49431380-4f1d-11ea-851a-1fbcf20b619f.png)
![image](https://user-images.githubusercontent.com/59091518/74495857-4bf13900-4f1c-11ea-9a88-69e7ed8d171c.png)
![image](https://user-images.githubusercontent.com/59091518/74495872-56abce00-4f1c-11ea-90b6-4a3bcf8bf1b4.png)

I already installed the sqlite3-dev , and also PKG_CONFIG_PATH was good, too.

please, can you tell me what should I do & what was the problem?

Thank you

**Comment by edzer** [comment] 2020-02-18 17:19
I can try if you provide a dockerfile that builds the system to reproduce your problem.

**Comment by gdk43** [comment] 2020-03-04 00:50
I'm really sorry for the late reply!!

I tried to install sf with a docker.
I don't know why, but I can't install docker because of a problem with the internet connection of the server, so I'm just installing it as rstudio.

Is there any solution we can do with rstudio?

**Comment by edzer** [comment] 2020-03-04 06:51
Have you followed the instructions for fedora given here: https://github.com/r-spatial/sf ?

**Comment by vwtlin** [comment] 2020-03-26 02:24
Hi all,

I have the same problem as well. My OS is macOS Catalina 10.15.4. I tried the R CMD install method but still, have the same problem. 
libproj not found in standard or given locations

<img width="1405" alt="Screen Shot 2020-03-26 at 10 20 06 am" src="https://user-images.githubusercontent.com/44833405/77603675-a635de80-6f4b-11ea-8e2a-ee502c4268d7.png">

Appreciate if anyone could help to provide any advice.

**Comment by EllaKaye** [comment] 2020-03-26 11:16
Hello. Same issue here. Only differences with @vwtlin is that I've got GDAL 3.0.4 and I'm on macOS Catalina 10.15.3. Thanks!

**Comment by NoodlesWang** [comment] 2020-03-27 01:37
Hello. Same issue as @EllaKaye . Got GDAL 3.0.4 and libproj not found.

**Comment by edzer** [comment] 2020-03-27 07:56
For all those who get here, use OSX, and don't know what is going on: please stick to using binary distributions; they typically show up on CRAN 1-2 weeks after new versions are distributed as source.

**Comment by caiohamamura** [comment] 2020-03-28 04:24
My travis build for OSX was working fine, but is also broken after `sf` update:

### Travis build
https://travis-ci.com/github/carlos-alberto-silva/rGEDI/jobs/306172914

### Travis file
https://github.com/carlos-alberto-silva/rGEDI/blob/fde6de4657e19354c2d7ee6fa7f116b90bbfd32b/.travis.yml

**Comment by caiohamamura** [comment] 2020-03-28 04:48
It seems like the build system is actually fine with gdal, proj and sqlite3 installed from the default package manager. Maybe the problem is within the `configure.ac` script itself.

If I may give you a suggestion, can't you change sqlite3 cheking for the default `ax_lib_sqlite3` from the [autoconf-archive](https://www.gnu.org/software/autoconf-archive/ax_lib_sqlite3.html#ax_lib_sqlite3).

GDAL also have a macro from the autoconf archive, and it also checks for minimum version. I always try to use those macros to avoid that kind of issues since they were already tested in multiple platforms.

**Comment by edzer** [comment] 2020-03-28 06:20
@caiohamamura feel free to submit a PR. Your travis testing is a bit quite a bit more extensive than sf's, and sf is moving to github actions. Note that many platforms suffer PROJ installations problems because of a bug in proj.pc / pkg-config installation present in released PROJ.

**Comment by rsbivand** [comment] 2020-03-28 10:20
Were you thinking of https://lists.osgeo.org/pipermail/proj/2020-March/009505.html?

**Closed** 2020-04-05 22:17 UTC

**Comment by ranghetti** [comment] 2020-10-20 16:30
Sorry for writing in a quite old thread, but I think I am encountering the same issue. I am trying to build a Docker image based on [GDAL Ubuntu full Docker](https://github.com/OSGeo/gdal/tree/master/gdal/docker/) with the manual addition of [rocker/geospatial](https://hub.docker.com/r/rocker/geospatial) features, in order to debug [{sen2r}](https://github.com/ranghetti/sen2r) on the more recent GDAL/PROJ environment (https://github.com/ranghetti/sen2r/issues/350). Here you find attached the dockerfile together with three patch files: [Docker_gdal_geospatial.zip](https://github.com/r-spatial/sf/files/5410111/Docker_gdal_geospatial.zip).

While installing {sf} from GitHub source, the following error occurs:
```
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)                                                                                                     
* installing *source* package ‘sf’ ...                                                                                        
** using staged installation                                                                                                  
configure: CC: gcc
configure: CXX: g++ -std=gnu++11
checking for gdal-config... /usr/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 3.2.0
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 3.2.0
configure: pkg-config proj exists, will use it
configure: using proj.h.
configure: PROJ: 7.2.0
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... no
configure: error: libproj or sqlite3 not found in standard or given locations.
ERROR: configuration failed for package ‘sf’
* removing ‘/usr/local/lib/R/site-library/sf’
* restoring previous ‘/usr/local/lib/R/site-library/sf’
Error: Failed to install 'sf' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmpdc99GY/file5e526a98cbd9/sf_0.9-7.tar.gz’ had non-zero exit status
Execution halted
```

If I understood well in https://github.com/r-spatial/sf/issues/1268#issuecomment-605426776, the issue should have ben fixed since PROJ 7.0.1, while I am using version 7.2.0.

Thank you for any possible advice,

**Comment by edzer** [comment] 2020-10-20 16:41
@ranghetti could you check whether `libsqlite3-dev` was installed in the container, and if not whether installing it resolves the problem?

**Comment by ranghetti** [comment] 2020-10-20 18:08
> @ranghetti could you check whether `libsqlite3-dev` was installed in the container, and if not whether installing it resolves the problem?

Yes, it was.

**Comment by edzer** [comment] 2020-10-20 19:41
OK. Does the Dockerfile reproduce the problem, or do I need to apply the patches to it first? If so, could you please provide the docker file after applying the patches?

**Comment by edzer** [comment] 2020-10-20 19:43
Ah, sorry, I see the patch files are used and applied inside the docker file...

**Comment by edzer** [comment] 2020-10-20 21:34
`libproj.so` is not found in a standard directory; it is in `/usr/local/lib`, but this is not specified with configure flags when installing sf.

**Comment by ranghetti** [comment] 2020-10-21 06:18
You are right, sorry. Nevertheless, this does not solve (using `remotes::install_github('r-spatial/sf', configure.args='--with-proj-lib=/usr/local/lib/')`, the same error is returned.
Maybe there are some incompatibilities between GDAL/PROJ local installation and packages installed subsequently:
```bash
root@2f59abfce005:/# sudo ldconfig -p | grep libproj
        libproj.so.19 (libc6,x86-64) => /usr/local/lib/libproj.so.19
        libproj.so.15 (libc6,x86-64) => /lib/x86_64-linux-gnu/libproj.so.15
```
where `/lib/x86_64-linux-gnu/libproj.so.15` was installed by `libproj15`, a `libspatialite7` dependency. 
I will search for additional information regarding the use of a GDAL/PROJ source installation and eventually open a specific issue.
Thank you

**Comment by Robinlovelace** [comment] 2020-10-21 13:19
Heads-up @ranghetti I've had a similar issue but with a different solution. Please take a look here if still of use/interest and try to reproduce with the steps outlined there: https://github.com/r-spatial/sf/issues/1518

Interested to hear if that works for you, I'm trying to tackle the issue as far upstream as possible with input to the `rocker-org/versioned2` repo as you'll see if you follow the links. Great to see others installing `sf` on on Docker images with recent versions of GDAL.

**Comment by ranghetti** [comment] 2020-10-22 04:59
Thank you @Robinlovelace for linking here the abovementioned issue. I tried your reproducible example in https://github.com/r-spatial/sf/issues/1518#issue-726392150, but unfortunately the error persists (I am commenting in https://github.com/r-spatial/sf/issues/1518 about that). The same in my example using the suggestion in https://github.com/r-spatial/sf/issues/1518#issuecomment-713509001.

**Comment by Evanaxe** [comment] 2020-12-02 18:31
For anyone else having this problem, I just solved it by setting the PKG_CONFIG_PATH environment:

export PKG_CONFIG_PATH=/path/to/proj/lib/pkgconfig/

**Comment by dchiu911** [comment] 2021-11-30 23:56
After much tedious trial and error, I think I may have a solution for those still running into this error. Two steps are necessary:

1. Compiling the dependency libraries with linking configured
2. Adding environment paths

I am using proj v8.1.1, sqlite3 v3.33.0 and gdal-config v3.3.2.

When compiling proj, add `/lib/pkgconfig/sqlite3.pc` to PKG_CONFIG_PATH otherwise `./configure` will fail
When compiling gdal, add `--with-python` and `--with-proj` flags to `./configure`.
Finally, add to `LD_LIBRARY_PATH` (also `LIBRARY_PATH`, `CPATH`, `PKG_CONFIG_PATH` but not as essential) the `lib` directory for proj, sqlite3 and gdal.

Then I got the following output:
```
* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: /gsc/software/linux-x86_64-centos7/gcc-7.2.0/bin/gcc
configure: CXX: /gsc/software/linux-x86_64-centos7/gcc-7.2.0/bin/g++ -std=gnu++11
checking for gdal-config... /home/dchiu/lib/gdal-3.3.2/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 3.3.2
checking GDAL version >= 2.0.1... yes
checking for gcc... /gsc/software/linux-x86_64-centos7/gcc-7.2.0/bin/gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /gsc/software/linux-x86_64-centos7/gcc-7.2.0/bin/gcc accepts -g... yes
checking for /gsc/software/linux-x86_64-centos7/gcc-7.2.0/bin/gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... /gsc/software/linux-x86_64-centos7/gcc-7.2.0/bin/gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /home/dchiu/lib/gdal-3.3.2/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 3.3.2
configure: pkg-config proj exists, will use it
configure: using proj.h.
configure: PROJ: 8.1.1
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... yes
checking for geos-config... /usr/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.4.2
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... yes
checking geos_c.h presence... yes
checking for geos_c.h... yes
checking geos: linking with -L/usr/lib64 -lgeos_c... yes
configure: Package CPP flags:  -I/home/dchiu/lib/proj/include   -DHAVE_PROJ_H -I/home/dchiu/lib/gdal-3.3.2/include -I/usr/include
configure: Package LIBS: -L/home/dchiu/lib/proj/lib -lproj     -L/home/dchiu/lib/gdal-3.3.2/lib -lgdal -L/usr/lib64 -lgeos_c
configure: creating ./config.status
config.status: creating src/Makevars
```
P.S. Using gdal v2.3.2 has the `/share/gdal/pcs.csv` data file although not needed to install `sf`

**Comment by AmethBin** [comment] 2022-04-08 08:55
For those who install proj and gdal with homebrew on M1/apple silicon, please try this one:
`install.packages('sf', configure.args = '--with-proj-include=/opt/homebrew/i
    nclude/ --with-proj-lib=/opt/homebrew/lib/', configure.vars = 'GDAL_DATA=/op
    t/homebrew/opt/gdal/share/gdal/')`
