### ISSUE TITLE
sp to sf using st_as_sf   issue

### ISSUE THREAD

**Issue by faridcher** [r-spatial/sf#636] opened 2018-02-01 22:16 UTC
Is it `sf` or is there a problem with the geometries created in `CharHull` function?

```r
install.packages("adehabitatHR")
library(adehabitatHR)
library(sf)
library(magrittr)

data(puechabonsp)

puechabonsp$relocs[,1] %>%
CharHull() ->
 res

res[[1]] %>% 
st_as_sf()
```

> Error in textConnection(text, encoding = "UTF-8") : 
  invalid 'text' argument
Called from: textConnection(text, encoding = "UTF-8")

thanks

**Comment by edzer** [comment] 2018-02-01 22:25
Please provide a complete reprex, and make sure it can be copied and pasted.

**Comment by faridcher** [comment] 2018-02-01 22:28
it reprex. `puechabonsp` dataset is part of `adehabitatHR`!

**Comment by edzer** [comment] 2018-02-01 22:47
No, it is missing the command `data(puechabonsp)` after loading `adehabitatHR`.

The problem is in the comments:
```r
> traceback()
12: textConnection(text, encoding = "UTF-8")
11: scan(text = cmt, quiet = TRUE)
10: Polygons2MULTIPOLYGON(y@Polygons, comment(y))
9: stopifnot(is.list(x) && all(vapply(x, is.list, TRUE)))
8: MtrxSetSet(x, dim, type = "MULTIPOLYGON", needClosed = TRUE)
7: st_multipolygon(Polygons2MULTIPOLYGON(y@Polygons, comment(y)))
6: FUN(X[[i]], ...)
5: lapply(x@polygons, function(y) st_multipolygon(Polygons2MULTIPOLYGON(y@Polygons, 
       comment(y))))
4: st_as_sfc.SpatialPolygons(sp::geometry(x), ...)
3: st_as_sfc(sp::geometry(x), ...)
2: st_as_sf.Spatial(res[[1]])
1: st_as_sf(res[[1]])
```
and is still present when
```r
st_as_sf(rgeos::createSPComment(res[[1]] ))
```
@rsbivand could you please check the comments are set all right on this object? I can't seem to find any, even though
```r
> comment(res[[1]])
[1] "TRUE"
```

**Comment by rsbivand** [comment] 2018-02-02 08:50
The first polygons object in each set of polygons objects (triangles mostly) has a NULL comment:

```
res <- CharHull(puechabonsp$relocs[,1])
any(sapply(slot(res[[1]], "polygons"), function(x) is.null(comment(x))))
# [1] TRUE
comment(slot(res[[1]], "polygons")[[2]])
# [1] "0"
comment(slot(res[[1]], "polygons")[[1]])
# NULL
comment(slot(res[[1]], "polygons")[[1]]) <- "0"
sp <- st_as_sf(res$Brock)
res <- CharHull(puechabonsp$relocs[,1])
sapply(res, function(S) any(sapply(slot(S, "polygons"), function(x) is.null(comment(x)))))
# Brock Calou  Chou  Jean 
# TRUE  TRUE  TRUE  TRUE 
sapply(res, function(S) which(sapply(slot(S, "polygons"), function(x) is.null(comment(x)))))
# Brock Calou  Chou  Jean 
#   1     1     1     1 
```

I haven't looked why CharHull() does this yet.

Repairing with `rgeos::createSPComment` fails because the comment on the SpatialPolygons object is set "TRUE":

```
comment(slot(res[[1]], "polygons")[[1]])
comment(res[[1]]) <- NULL
res[[1]] <- createSPComment(res[[1]])
comment(slot(res[[1]], "polygons")[[1]])
```

**Comment by rsbivand** [comment] 2018-02-02 12:46
Runs fine with this patch in `sp/R/SpatialPolygons-methods.R`- the original test was `any`, but should have been `all`. This didn't cause the problem, but prevented its correction with `rgeos::createSPComment`:

```
# 120416 add top-level comment to reduce comment checking
	cSr <- as.character(all(sapply(slot(res, "polygons"),
# 180201 change any to all after NULL comment found
            function(x) !is.null(comment(x))), na.rm=TRUE))
```

In `adehabitatHR/R/CharHull.r` `adehabitatHR::CharHull() generates the NULL comment at a list initiation. At line 95, `spP <- do.call("rbind", lip)` generates the SpatialPolygons object that has no comment on the first Polygons object. `lip` is a list of SpatialPolygons objects. 

sp::rbind.SpatialPolygons does not check comments, so paases through 

```
Browse[2]> comment(lip[[1]])
[1] "FALSE"
Browse[2]> comment(lip[[1]]@polygons[[1]])
NULL
```

and then falls into the any/all bug in the `SpatialPolygons` constructor function. The equivalent patch for `SpatialPolygonsDataFrame()` is:

```
        cSr <- comment(Sr)
        if (is.null(cSr))
            comment(res) <- as.character(all(sapply(slot(res, "polygons"),
# 180201 change any to all after NULL comment found
                function(x) !is.null(comment(x))), na.rm=TRUE))
        else {
            if (!is.character(cSr) || is.na(cSr) || length(cSr) != 1)
            cSr <- as.character(all(sapply(slot(res, "polygons"),
# 180201 change any to all after NULL comment found
                function(x) !is.null(comment(x))), na.rm=TRUE))
            comment(res) <- cSr
        }
```

**Comment by edzer** [comment] 2018-02-02 18:25
Thanks, @rsbivand - I've committed it.

**Closed** 2018-02-02 18:25 UTC
