### ISSUE TITLE
Error while trying to write a geospatial table with a foreign key

### ISSUE THREAD

**Issue by asitemade4u** [r-spatial/sf#1210] opened 2019-12-03 23:54 UTC
#### Context

- I am trying to write a SF dataframe to a geospatial table, "HOS", belonging to a PostgreSQL/Postgis database.
- The table belongs to a schema, "PLC".
- The table "HOS" has a foreign key "poi_key" pointing to another table, "POI". POI is a plain non-geospatial table in the same PostgreSQL database.

#### What I am doing

1. I begin by extracting what is relevant to the table "POI" from the dataframe and populate/append data to the table "POI". I manually input the values into poi_key by incrementing them. They are unique. 
The appending to the POI table is done using:

   ```R
   DBI::dbWriteTable(conn = cnx, name = c(thesch, thetbl), value = thedtf, overwrite = over, append = !over, row.names = F)
   ```

   Works fine and I checked the rows are duly created.

1. Then I try to add the geospatial data in the table "HOS".
   For that purpose I do:

   ```R
   sf::st_write(obj = thedtf, dsn = cnx, table = c(thesch, thetbl), row.names = F, overwrite = over, append = !over)
   ```

 where:

   | variable | value | explanation                                                  |
   | -------- | ----- | ------------------------------------------------------------ |
   | thedtf   |       | the dataframe, with the exact same column names as the columns in the HOS table |
   | cnx      |       | the connection which works, because I checked and already used the same connection process at #1     |
   | thesch   | plc   | the schema the table belongs to                              |
   | thetbl   | hos   | the table                                                    |
   | over     | FALSE | instruction to overwrite or not. Append is "over" negated      |

   Then I get this error, which prevents the dataframe to be appended to the table:
  ```
   Error in postgresqlpqExec(new.con, sql4) : 
     RS-DBI driver: (could not Retrieve the result : ERROR:  column "poi_key" of relation "thedtf" does not exist)
   ```

#### I checked everything

* the values are correct
* the names of the columns are mirrored in the dataframe
* the foreign key poi_key points to existing rows in the table POI

What am I doing wrong?

Please help as I am stuck.
Stephen

**Comment by edzer** [comment] 2019-12-09 09:38
@etiennebr is this something that rings a bell with you?

**Comment by etiennebr** [comment] 2019-12-09 13:47
It looks like you are using the `PostgreSQL` driver. Could you try to create your connection with `con <- DBI::dbConnect(RPostgres::Postgres())`. Note that you must refer to the schema using `DBI::Id()` with `RPostgres`.
``` r
DBI::dbWriteTable(conn = cnx, name = DBI::Id(schema = thesch, table = thetbl), value = thedtf, overwrite = over, append = !over, row.names = F)
```

I'd be happy to have a look. It would really help if you could come up with a minimal reprex, maybe you'll even solve the problem that way.

**Comment by asitemade4u** [comment] 2019-12-09 13:50
Thanks for the response!

I am indeed very confused with the coexistence of TWO different drivers 
to PostgreSQL within the R ecosystem...

Also, could you explain how to issue a "minimal reprex": I am a 
developer bu not geared toward databases till now ;o))

Merci Etienne (je suis francais, vivant aux States).

S.

**Comment by etiennebr** [comment] 2019-12-10 02:34
Bonjour Stephen!

Maybe your issue is because you use the `table` argument rather than `layer`. See my minimal reprex (that works). (I'm using the docker container `kartoza/postgis` to run this example.) See if it works for you or if you can reproduce your bug.
``` r
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.4.2, PROJ 5.2.0
library(DBI)

con <- DBI::dbConnect(RPostgres::Postgres(), host = "localhost", dbname = "gis", port = 25432, user = "docker")

# create sch.hos with poi_key column
dbExecute(con, "CREATE SCHEMA sch")
#> [1] 0
dbExecute(con, "CREATE TABLE sch.hos AS SELECT 1 as id, 'POINT(1 2)'::geometry")
#> [1] 1
# create poi table
dbExecute(con, "CREATE TABLE poi AS SELECT 1 as id")
#> [1] 1
dbExecute(con, "INSERT INTO poi (SELECT 2 as id)")
#> [1] 1
dbExecute(con, "ALTER TABLE poi ADD PRIMARY KEY (id)")
#> [1] 0
# add foreign key
dbExecute(con, "ALTER TABLE sch.hos ADD FOREIGN KEY (id) REFERENCES poi (id)")
#> [1] 0

# try to insert
st_write(st_sf(id = 4, geometry = st_sfc(st_point(2:3))), con, layer =  DBI::Id(schema = "sch", table = "hos"), append = TRUE)
#> Note: method with signature 'DBIObject#sf' chosen for function 'dbDataType',
#>  target signature 'PqConnection#sf'.
#>  "PqConnection#ANY" would also be valid
#> Error in connection_copy_data(conn@ptr, sql, value): COPY returned error: ERROR:  insert or update on table "hos" violates foreign key constraint "hos_id_fkey"
#> DETAIL:  Key (id)=(4) is not present in table "poi".
st_write(st_sf(id = 2, geometry = st_sfc(st_point(2:3))), con, layer =  DBI::Id(schema = "sch", table = "hos"), append = TRUE)

# clear
dbExecute(con, "DROP TABLE poi CASCADE")
#> [1] 0
dbExecute(con, "DROP schema sch CASCADE")
#> [1] 0
```

**Comment by edzer** [comment] 2020-01-11 16:53
Can we close this?

**Comment by asitemade4u** [comment] 2020-01-12 00:06
Yes you can, and I thank you very much for the help!

**Closed** 2020-01-12 09:14 UTC
Labels: reprex
