### ISSUE TITLE
Problem using st_as_sf with non-closed polygons or  fixed non-closed polygons

### ISSUE THREAD

**Issue by urskalbitzer** [r-spatial/sf#430] opened 2017-07-19 04:40 UTC
First of all: sf is a great package. I only recently started to play around with spatial data and I was so happy to discover the sf package. I use dplyr a lot, so it's much easier for me to work with sf-objects than with sp-objects.
Anyway, I'm trying get a worldmap as sf-object. I chose to get the map from the rworldmap package. This map, unfortunately, has some non-closed polygons and cannot be transformed into a sf-object:
```{r}
worldmap <- rworldmap::getMap()
worldmap_sf <- sf::st_as_sf(worldmap)
```
> Error in MtrxSetSet(x, dim, type = "MULTIPOLYGON", needClosed = TRUE) : polygons not (all) closed

Therefore, I first fixed the non-closed polygons using the cleangeo package. When I try to transform the cleaned SPDF into an object of the class 'sf', it produces this error:
```{r}
worldmap <- rworldmap::getMap()
worldmap <- cleangeo::clgeo_Clean(worldmap)
worldmap_sf <- sf::st_as_sf(worldmap)
```
> Error in textConnection(text, encoding = "UTF-8") : invalid 'text' argument

I know there are other possibilities to get a worldmap, possibly without the problem of non-closed polygons, but I thought to report it here in case this is not the desired behavior of the st_as_sf function. If this is the desired behavior, I think a more informative error-message (especially in the second case) would be very helpful.

Thanks a lot, Urs

**Comment by edzer** [comment] 2017-07-19 06:36
Calling in the respective package maintainers, @AndySouth and @eblondel -- am I right these are not problems caused by `sf`? 

@AndySouth, why is e.g. Western Sahara not closed (138)?

@eblondel, after cleaning we see
```r
> which(sapply(sapply(worldmap@polygons, comment), is.null))
[1]  28 137
```
which was not the case for the original rworldmap. 28 is Canada. Sf assumes either all comments are present, or none.

**Comment by urskalbitzer** [comment] 2017-07-19 17:08
Thanks a lot for looking at this so quickly and calling in the respective package maintainers. Maybe they can provide a solution to obtain the rworldmap as an sf-object.
And I'm living in Canada, so I would be very happy if it still has its name after fixing the worldmap.

**Comment by eblondel** [comment] 2017-07-20 17:02
Hello @edzer in order to reproduce the error, i would need info on the environment, session info and package versions. I've tried with an older release (3.2.2), and used rworldmap 1.3.1. About geometry validity, in my case only feature 28 appears invalid in original object. It is fixed with cleaning. 

I need to check about the comment. I get a warning indicating an absence of comment for hole for feature 28 if i run ``gIsValid`` on the cleaned object, but there is no hole in the polygon 28. If I check geometry validity of each feature polygon, all are valid. I couldn't test ``sf::st_as_sf```. I would try it by excluding the features highlighted in your reply, first to see if they are responsible of the error. Simple feature is not dealing with topology check, but at feature level if i'm right, so a polygon valid with rgeos means it is closed and should be valid and converted well to sf. AFAIK another cross-check would be to try to write as WKT, it would fail for a non-closed polygon.

ASAP i will try to perform more tests and let you know if i find smthg relevant.

**Comment by AndySouth** [comment] 2017-07-24 17:47
Thanks All,

Apologies for delayed response I'm travelling and teaching for a couple of
weeks.

The polygon boundaries come from Natural Earth
http://www.naturalearthdata.com/

I have a newer package on CRAN rnaturalearth which gives better access to
these data (but may have similar or worse problems).

rworldmap uses maptools::checkPolygonsHoles

rnaturalearth doesn't, but does use newer data.

If there are still unclosed polygons I can report to the naturalearthdata
maintainers.

Andy

**Comment by urskalbitzer** [comment] 2017-07-24 18:58
I had a look at the rnaturalworld package and the new map works well with st_as_sf:
```{r}
worldmap <- rnaturalearth::ne_download(scale = 110,
                                       type = "countries",
                                       category = "cultural",
                                       destdir = tempdir(),
                                       load = TRUE,
                                       returnclass = "sp")

worldmap_sf <- sf::st_as_sf(worldmap)
```
works without any problems.

Even better, I can use the following to directly get the world map as sf-object:
```{r}
worldmap <- rnaturalearth::ne_download(scale = 110,
                                       type = "countries",
                                       category = "cultural",
                                       destdir = tempdir(),
                                       load = TRUE,
                                       returnclass = "sf")
```

Thanks a lot for your help,
Urs

**Comment by edzer** [comment] 2017-07-24 19:01
Cool, thanks!

**Closed by edzer** 2017-07-24 19:01 UTC

**Comment by rsbivand** [comment] 2017-07-24 19:24
With the rnaturalearth data, I only see India as invalid with scale=50, and this is fixed with st_make_valid(). Otherwise OK.
