### ISSUE TITLE
Error in rename.sf(., newname = oldname) :    internal error: can't find `agr` columns

### ISSUE THREAD

**Issue by rungec** [r-spatial/sf#1509] opened 2020-10-12 00:00 UTC
k_fix <- k_fix %>% rename(newname = oldname)
Error in rename.sf(., newname = oldname) : 
  internal error: can't find `agr` columns

The weird thing is I have two columns I am renaming, and the first column works fine. 
k_fix <- left_join(k_fix, re_1_group, by='cellid')
k_fix <- left_join(k_fix, re_2_group, by='cellid')
k_fix <- k_fix %>% rename(newname1 = oldname1) *works
k_fix <- k_fix %>% rename(newname2 = oldname2) *doesnt work

Both columns are numeric and contains some NA and I am renaming after left_join() . k_fix is a reasonably big 1.7million rows of polygons.
> class(k_fix)
[1] "sf"         "tbl_df"     "tbl"        "data.frame"
> summary(attr(k_fix, 'agr'))
 constant aggregate  identity      NA's 
        0              0              0            35 
Any suggestions for where to start troubleshooting?

**Comment by Robinlovelace** [comment] 2020-10-12 08:17
Do you have a minimum reproducible example? That could help identify and potentially debug the exactly cause of the issue.

**Comment by edzer** [comment] 2020-10-12 09:17
And we need your sessionInfo(), as this might have been fixed in #1483

**Comment by edzer** [comment] 2020-12-02 13:03
Closing in lack of response.

**Closed by edzer** 2020-12-02 13:03 UTC

**Comment by moritzpoll** [comment] 2021-01-14 16:07
The same is happening to me as well on one machine, but not on the other. Here is my code:
```
county_shp <- st_make_valid(st_read("<PATH>"))
county_shp <- county_shp %>% rename(county = name)
```

internal error: can't find agr columns

And here is the sessionInfo() on the machine where it doesn't work:

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] topicmodels_0.2-11 tidytext_0.2.6     stargazer_5.2.2    RColorBrewer_1.1-2 leaflet_2.0.3      tmap_3.2          
 [7] ggmap_3.0.0        sf_0.9-7           visdat_0.5.3       labelled_2.7.0     forcats_0.5.0      stringr_1.4.0     
[13] dplyr_1.0.2        purrr_0.3.4        tidyr_1.1.2        tibble_3.0.4       tidyverse_1.3.0    Hmisc_4.4-2       
[19] ggplot2_3.3.2      Formula_1.2-4      survival_3.2-7     lattice_0.20-41    haven_2.3.1        expss_0.10.7      
[25] readr_1.4.0       

loaded via a namespace (and not attached):
 [1] leafem_0.1.3            colorspace_2.0-0        rjson_0.2.20            ellipsis_0.3.1          class_7.3-17           
 [6] modeltools_0.2-23       htmlTable_2.1.0         base64enc_0.1-3         fs_1.5.0                dichromat_2.0-0        
[11] rstudioapi_0.13         SnowballC_0.7.0         fansi_0.4.1             lubridate_1.7.9.2       xml2_1.3.2             
[16] codetools_0.2-16        splines_4.0.3           knitr_1.30              jsonlite_1.7.2          tmaptools_3.1          
[21] broom_0.7.2             cluster_2.1.0           dbplyr_2.0.0            png_0.1-7               compiler_4.0.3         
[26] httr_1.4.2              backports_1.2.1         assertthat_0.2.1        Matrix_1.2-18           cli_2.2.0              
[31] leaflet.providers_1.9.0 htmltools_0.5.0         tools_4.0.3             NLP_0.2-1               gtable_0.3.0           
[36] glue_1.4.2              Rcpp_1.0.5              slam_0.1-48             cellranger_1.1.0        raster_3.4-5           
[41] vctrs_0.3.5             leafsync_0.1.0          crosstalk_1.1.0.1       lwgeom_0.2-5            xfun_0.19              
[46] rvest_0.3.6             lifecycle_0.2.0         XML_3.99-0.5            scales_1.1.1            hms_0.5.3              
[51] parallel_4.0.3          gridExtra_2.3           rpart_4.1-15            latticeExtra_0.6-29     stringi_1.5.3          
[56] tokenizers_0.2.1        e1071_1.7-4             checkmate_2.0.0         RgoogleMaps_1.4.5.3     rlang_0.4.9            
[61] pkgconfig_2.0.3         matrixStats_0.57.0      bitops_1.0-6            htmlwidgets_1.5.3       tidyselect_1.1.0       
[66] plyr_1.8.6              magrittr_2.0.1          R6_2.5.0                generics_0.1.0          DBI_1.1.0              
[71] pillar_1.4.7            foreign_0.8-80          withr_2.3.0             units_0.6-7             stars_0.4-3            
[76] abind_1.4-5             sp_1.4-4                nnet_7.3-14             janeaustenr_0.1.5       modelr_0.1.8           
[81] crayon_1.3.4            KernSmooth_2.23-17      jpeg_0.1-8.1            grid_4.0.3              readxl_1.3.1           
[86] data.table_1.13.4       reprex_0.3.0            digest_0.6.27           classInt_0.4-3          tm_0.7-8               
[91] stats4_4.0.3            munsell_0.5.0           viridisLite_0.3.0    
```

Compared to the sessionInfo() on the machine that I haven't updated in a while but where it all works as it should:

> R version 3.6.3 (2020-02-29)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS Mojave 10.14.6
> 
> Matrix products: default
> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] topicmodels_0.2-11 tidytext_0.2.4     stargazer_5.2.2    RColorBrewer_1.1-2
>  [5] leaflet_2.0.3.9000 tmap_3.0           ggmap_3.0.0        sf_0.9-3          
>  [9] visdat_0.5.3       labelled_2.5.0     forcats_0.5.0      stringr_1.4.0     
> [13] dplyr_1.0.0.9000   purrr_0.3.4        tidyr_1.1.0        tibble_3.0.3      
> [17] tidyverse_1.3.0    Hmisc_4.4-0        ggplot2_3.3.0      Formula_1.2-3     
> [21] survival_3.1-8     lattice_0.20-38    haven_2.3.1        expss_0.10.5      
> [25] readr_1.3.1       
> 
> loaded via a namespace (and not attached):
>  [1] leafem_0.1.1        colorspace_1.4-1    rjson_0.2.20        ellipsis_0.3.1     
>  [5] class_7.3-15        modeltools_0.2-23   htmlTable_1.13.3    base64enc_0.1-3    
>  [9] fs_1.4.1            dichromat_2.0-0     rstudioapi_0.11     SnowballC_0.7.0    
> [13] fansi_0.4.1         lubridate_1.7.8     xml2_1.3.1          codetools_0.2-16   
> [17] splines_3.6.3       knitr_1.28          jsonlite_1.6.1      tmaptools_3.0      
> [21] broom_0.5.5         cluster_2.1.0       dbplyr_1.4.4        png_0.1-7          
> [25] compiler_3.6.3      httr_1.4.1          backports_1.1.5     assertthat_0.2.1   
> [29] Matrix_1.2-18       cli_2.0.2           acepack_1.4.1       htmltools_0.4.0    
> [33] tools_3.6.3         NLP_0.2-0           gtable_0.3.0        glue_1.4.1         
> [37] Rcpp_1.0.5          slam_0.1-47         cellranger_1.1.0    raster_3.0-12      
> [41] vctrs_0.3.1         nlme_3.1-144        leafsync_0.1.0      crosstalk_1.1.0.1  
> [45] lwgeom_0.2-3        xfun_0.12           rvest_0.3.5         lifecycle_0.2.0    
> [49] XML_3.99-0.3        scales_1.1.0        hms_0.5.3           parallel_3.6.3     
> [53] gridExtra_2.3       rpart_4.1-15        latticeExtra_0.6-29 stringi_1.4.6      
> [57] tokenizers_0.2.1    e1071_1.7-3         checkmate_2.0.0     RgoogleMaps_1.4.5.3
> [61] rlang_0.4.7         pkgconfig_2.0.3     matrixStats_0.56.0  bitops_1.0-6       
> [65] htmlwidgets_1.5.1   tidyselect_1.1.0    plyr_1.8.6          magrittr_1.5       
> [69] R6_2.4.1            generics_0.0.2      DBI_1.1.0           pillar_1.4.6       
> [73] foreign_0.8-75      withr_2.1.2         units_0.6-6         stars_0.4-1        
> [77] abind_1.4-5         sp_1.4-2            nnet_7.3-12         janeaustenr_0.1.5  
> [81] modelr_0.1.6        crayon_1.3.4        KernSmooth_2.23-16  jpeg_0.1-8.1       
> [85] grid_3.6.3          readxl_1.3.1        data.table_1.12.8   blob_1.2.1         
> [89] reprex_0.3.0        digest_0.6.25       classInt_0.4-3      tm_0.7-7           
> [93] stats4_3.6.3        munsell_0.5.0       viridisLite_0.3.0  

Let me know if there is anything else you may need to help you resolve this.

**Comment by edzer** [comment] 2021-01-14 21:18
Need a reprex.

**Comment by moritzpoll** [comment] 2021-01-15 09:43
Of course. Data set comes from here: [https://www.arcgis.com/home/item.html?id=5f83ca29e5b849b8b05bc0b281ae27bc](url)

```
rm(list = ls())
packages <- c("readr", "expss", "haven", "Hmisc", "tidyverse", "tidyr", "stringr", "forcats", "labelled", "visdat", "tibble", "sf", "ggmap", "tmap", "leaflet", "RColorBrewer", "stargazer", "tidytext", "topicmodels")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) install.packages(setdiff(packages, rownames(installed.packages())))
lapply(packages, require, character.only = TRUE)

county_shp <- st_make_valid(st_read("<PATH>")) # https://www.arcgis.com/home/item.html?id=5f83ca29e5b849b8b05bc0b281ae27bc
colnames(county_shp) <- tolower(colnames(county_shp))
county_shp <- county_shp %>% rename(county = name) %>% subset(select = -c(id, fid, objectid))
```

**Comment by Robinlovelace** [comment] 2021-01-15 09:51
I tried and failed to reproduce the code provided. I think the addition of a line containing `download.file(url_file)` and updating the file path could make it fully reproducible.

<details>

``` r
rm(list = ls())
packages <- c("readr", "expss", "haven", "Hmisc", "tidyverse", "tidyr", "stringr", "forcats", "labelled", "visdat", "tibble", "sf", "ggmap", "tmap", "leaflet", "RColorBrewer", "stargazer", "tidytext", "topicmodels")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) install.packages(setdiff(packages, rownames(installed.packages())))
#> Installing packages into '/home/robin/R/x86_64-pc-linux-gnu-library/4.0'
#> (as 'lib' is unspecified)
#> also installing the dependencies 'NLP', 'slam', 'tm'
#> Warning in install.packages(setdiff(packages, rownames(installed.packages()))):
#> installation of package 'topicmodels' had non-zero exit status
lapply(packages, require, character.only = TRUE)
#> Loading required package: readr
#> Loading required package: expss
#> Loading required package: haven
#> 
#> Attaching package: 'haven'
#> The following objects are masked from 'package:expss':
#> 
#>     is.labelled, read_spss
#> Loading required package: Hmisc
#> Loading required package: lattice
#> Loading required package: survival
#> Loading required package: Formula
#> Loading required package: ggplot2
#> 
#> Attaching package: 'ggplot2'
#> The following object is masked from 'package:expss':
#> 
#>     vars
#> Registered S3 methods overwritten by 'Hmisc':
#>   method                 from 
#>   [.labelled             expss
#>   print.labelled         expss
#>   as.data.frame.labelled expss
#> 
#> Attaching package: 'Hmisc'
#> The following objects are masked from 'package:base':
#> 
#>     format.pval, units
#> Loading required package: tidyverse
#> Loading required package: labelled
#> 
#> Attaching package: 'labelled'
#> The following object is masked from 'package:expss':
#> 
#>     is.labelled
#> Loading required package: visdat
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
#> Loading required package: ggmap
#> Google's Terms of Service: https://cloud.google.com/maps-platform/terms/.
#> Please cite ggmap if you use it! See citation("ggmap") for details.
#> Loading required package: tmap
#> Loading required package: leaflet
#> Loading required package: RColorBrewer
#> Loading required package: stargazer
#> 
#> Please cite as:
#>  Hlavac, Marek (2018). stargazer: Well-Formatted Regression and Summary Statistics Tables.
#>  R package version 5.2.2. https://CRAN.R-project.org/package=stargazer
#> Loading required package: tidytext
#> Loading required package: topicmodels
#> Warning in library(package, lib.loc = lib.loc, character.only = TRUE,
#> logical.return = TRUE, : there is no package called 'topicmodels'
#> [[1]]
#> [1] TRUE
#> 
#> [[2]]
#> [1] TRUE
#> 
#> [[3]]
#> [1] TRUE
#> 
#> [[4]]
#> [1] TRUE
#> 
#> [[5]]
#> [1] TRUE
#> 
#> [[6]]
#> [1] TRUE
#> 
#> [[7]]
#> [1] TRUE
#> 
#> [[8]]
#> [1] TRUE
#> 
#> [[9]]
#> [1] TRUE
#> 
#> [[10]]
#> [1] TRUE
#> 
#> [[11]]
#> [1] TRUE
#> 
#> [[12]]
#> [1] TRUE
#> 
#> [[13]]
#> [1] TRUE
#> 
#> [[14]]
#> [1] TRUE
#> 
#> [[15]]
#> [1] TRUE
#> 
#> [[16]]
#> [1] TRUE
#> 
#> [[17]]
#> [1] TRUE
#> 
#> [[18]]
#> [1] TRUE
#> 
#> [[19]]
#> [1] FALSE

county_shp <- st_make_valid(st_read("<PATH>")) # https://www.arcgis.com/home/item.html?id=5f83ca29e5b849b8b05bc0b281ae27bc
#> Error: Cannot open "<PATH>"; The file doesn't seem to exist.
colnames(county_shp) <- tolower(colnames(county_shp))
#> Error in is.data.frame(x): object 'county_shp' not found
county_shp <- county_shp %>% rename(county = name) %>% subset(select = -c(id, fid, objectid))
#> Error in rename(., county = name): object 'county_shp' not found
```

<sup>Created on 2021-01-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by moritzpoll** [comment] 2021-01-15 11:31
Sorry, the URL doesn't seem to work in the download.file() function (or directly in the st_read() function for that matter). Any chance you could download the data manually, unzip it and fill in the file path where I put <PATH>? Thanks!

**Comment by Robinlovelace** [comment] 2021-01-15 13:55
Can you reproduce the data with another input dataset? Or you could upload a .zip file containing the data in response to the comment for full reproducibility. Could do but busy day and I think the onus should be on people submitting issues to demonstrate the issue, in a reproducible way if possible.

**Comment by moritzpoll** [comment] 2021-01-15 14:51
Of course, you may want to set a working directory. Let me know if this works:

```
rm(list = ls())
packages <- c("readr", "expss", "haven", "Hmisc", "tidyverse", "tidyr", "stringr", "forcats", "labelled", "visdat", "tibble", "sf", "ggmap", "tmap", "leaflet", "RColorBrewer", "stargazer", "tidytext", "topicmodels")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) install.packages(setdiff(packages, rownames(installed.packages())))
lapply(packages, require, character.only = TRUE)
download.file("https://www.arcgis.com/sharing/rest/content/items/5f83ca29e5b849b8b05bc0b281ae27bc/data", paste0(getwd(),"/County.zip"))
unzip(paste0(getwd(),"/County.zip"), exdir = getwd())
county_shp <- st_make_valid(st_read(paste0(getwd(),"/County")))
colnames(county_shp) <- tolower(colnames(county_shp))
county_shp <- county_shp %>% rename(county = name) %>% subset(select = -c(id, fid, objectid))
```

Here is the output on my end:
```

> download.file("https://www.arcgis.com/sharing/rest/content/items/5f83ca29e5b849b8b05bc0b281ae27bc/data", paste0(getwd(),"/County.zip"))
trying URL 'https://www.arcgis.com/sharing/rest/content/items/5f83ca29e5b849b8b05bc0b281ae27bc/data'
Content type 'application/zip' length 538044 bytes (525 KB)
==================================================
downloaded 525 KB

> unzip(paste0(getwd(),"/County.zip"), exdir = getwd())
> county_shp <- st_make_valid(st_read(paste0(getwd(),"/County")))
Reading layer `County' from data source `/Users/moritz/County' using driver `ESRI Shapefile'
Simple feature collection with 47 features and 8 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: 33.91028 ymin: -4.798828 xmax: 41.90613 ymax: 5.414124
geographic CRS: WGS 84
> colnames(county_shp) <- tolower(colnames(county_shp))
> county_shp <- county_shp %>% rename(county = name) %>% subset(select = -c(id, fid, objectid))
Error in rename.sf(., county = name) : 
  internal error: can't find `agr` columns
```

**Comment by Robinlovelace** [comment] 2021-01-15 17:16
Thanks @moritzpoll Just trying to reproduce it like this (tip, try out the reprex package):

```r
reprex::reprex({
  
rm(list = ls())
packages <- c("readr", "expss", "haven", "Hmisc", "tidyverse", "tidyr", "stringr", "forcats", "labelled", "visdat", "tibble", "sf", "ggmap", "tmap", "leaflet", "RColorBrewer", "stargazer", "tidytext", "topicmodels")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) install.packages(setdiff(packages, rownames(installed.packages())))
lapply(packages, require, character.only = TRUE)
download.file("https://www.arcgis.com/sharing/rest/content/items/5f83ca29e5b849b8b05bc0b281ae27bc/data", paste0(getwd(),"/County.zip"))
unzip(paste0(getwd(),"/County.zip"), exdir = getwd())
county_shp <- st_make_valid(st_read(paste0(getwd(),"/County")))
colnames(county_shp) <- tolower(colnames(county_shp))
county_shp <- county_shp %>% rename(county = name) %>% subset(select = -c(id, fid, objectid))

})
```

**Comment by Robinlovelace** [comment] 2021-01-15 17:17
Confirmed I can reproduce the issue :tada: 

Is this intended behaviour @edzer ?

``` r
  
rm(list = ls())
packages <- c("readr", "expss", "haven", "Hmisc", "tidyverse", "tidyr", "stringr", "forcats", "labelled", "visdat", "tibble", "sf", "ggmap", "tmap", "leaflet", "RColorBrewer", "stargazer", "tidytext", "topicmodels")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) install.packages(setdiff(packages, rownames(installed.packages())))
#> Installing package into '/home/robin/R/x86_64-pc-linux-gnu-library/4.0'
#> (as 'lib' is unspecified)
#> Warning in install.packages(setdiff(packages, rownames(installed.packages()))):
#> installation of package 'topicmodels' had non-zero exit status
lapply(packages, require, character.only = TRUE)
#> Loading required package: readr
#> Loading required package: expss
#> Loading required package: haven
#> 
#> Attaching package: 'haven'
#> The following objects are masked from 'package:expss':
#> 
#>     is.labelled, read_spss
#> Loading required package: Hmisc
#> Loading required package: lattice
#> Loading required package: survival
#> Loading required package: Formula
#> Loading required package: ggplot2
#> 
#> Attaching package: 'ggplot2'
#> The following object is masked from 'package:expss':
#> 
#>     vars
#> Registered S3 methods overwritten by 'Hmisc':
#>   method                 from 
#>   [.labelled             expss
#>   print.labelled         expss
#>   as.data.frame.labelled expss
#> 
#> Attaching package: 'Hmisc'
#> The following objects are masked from 'package:base':
#> 
#>     format.pval, units
#> Loading required package: tidyverse
#> Loading required package: labelled
#> 
#> Attaching package: 'labelled'
#> The following object is masked from 'package:expss':
#> 
#>     is.labelled
#> Loading required package: visdat
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
#> Loading required package: ggmap
#> Google's Terms of Service: https://cloud.google.com/maps-platform/terms/.
#> Please cite ggmap if you use it! See citation("ggmap") for details.
#> Loading required package: tmap
#> Loading required package: leaflet
#> Loading required package: RColorBrewer
#> Loading required package: stargazer
#> 
#> Please cite as:
#>  Hlavac, Marek (2018). stargazer: Well-Formatted Regression and Summary Statistics Tables.
#>  R package version 5.2.2. https://CRAN.R-project.org/package=stargazer
#> Loading required package: tidytext
#> Loading required package: topicmodels
#> Warning in library(package, lib.loc = lib.loc, character.only = TRUE,
#> logical.return = TRUE, : there is no package called 'topicmodels'
#> [[1]]
#> [1] TRUE
#> 
#> [[2]]
#> [1] TRUE
#> 
#> [[3]]
#> [1] TRUE
#> 
#> [[4]]
#> [1] TRUE
#> 
#> [[5]]
#> [1] TRUE
#> 
#> [[6]]
#> [1] TRUE
#> 
#> [[7]]
#> [1] TRUE
#> 
#> [[8]]
#> [1] TRUE
#> 
#> [[9]]
#> [1] TRUE
#> 
#> [[10]]
#> [1] TRUE
#> 
#> [[11]]
#> [1] TRUE
#> 
#> [[12]]
#> [1] TRUE
#> 
#> [[13]]
#> [1] TRUE
#> 
#> [[14]]
#> [1] TRUE
#> 
#> [[15]]
#> [1] TRUE
#> 
#> [[16]]
#> [1] TRUE
#> 
#> [[17]]
#> [1] TRUE
#> 
#> [[18]]
#> [1] TRUE
#> 
#> [[19]]
#> [1] FALSE
download.file("https://www.arcgis.com/sharing/rest/content/items/5f83ca29e5b849b8b05bc0b281ae27bc/data", paste0(getwd(),"/County.zip"))
unzip(paste0(getwd(),"/County.zip"), exdir = getwd())
county_shp <- st_make_valid(st_read(paste0(getwd(),"/County")))
#> Reading layer `County' from data source `/tmp/RtmpbIoTSH/reprex38091fe97eb9/County' using driver `ESRI Shapefile'
#> Simple feature collection with 47 features and 8 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: 33.91028 ymin: -4.798828 xmax: 41.90613 ymax: 5.414124
#> geographic CRS: WGS 84
colnames(county_shp) <- tolower(colnames(county_shp))
county_shp <- county_shp %>% rename(county = name) %>% subset(select = -c(id, fid, objectid))
#> Error in rename.sf(., county = name): internal error: can't find `agr` columns
```

<sup>Created on 2021-01-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment] 2021-01-15 21:15
Leave out the
```
colnames(county_shp) <- tolower(colnames(county_shp))
```
use the proper cases in the following command, and it will work. `colnames<-` leads to broken `sf` objects. It's not tidy anyway.

**Comment by edzer** [comment] 2021-01-15 21:16
Also, a proper reprex doesn't install dozens of packages that it doesn't need.

**Comment by moritzpoll** [comment] 2021-01-16 05:48
Thank you both! This was very helpful. Much appreciated.

**Comment by jebyrnes** [comment] 2021-03-26 13:58
This seems to still be an issue. Here is a simple reprex (which is a class example that worked last year at this time)

``` r
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.1.2, PROJ 7.1.1
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(USAboundaries)



map_sf <-  us_counties() %>%
  rename(State = state_name,
         County = name)
#> Error in rename.sf(., State = state_name, County = name): internal error: can't find `agr` columns
```

<sup>Created on 2021-03-26 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>


Aaaand

```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] USAboundaries_0.3.1 dplyr_1.0.5         sf_0.9-9           

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6         magrittr_2.0.1     units_0.7-1        tidyselect_1.1.0  
 [5] R6_2.5.0           rlang_0.4.10       fansi_0.4.2        tools_4.0.3       
 [9] parallel_4.0.3     grid_4.0.3         KernSmooth_2.23-17 utf8_1.2.1        
[13] e1071_1.7-6        DBI_1.1.1          ellipsis_0.3.1     class_7.3-17      
[17] assertthat_0.2.1   yaml_2.2.1         tibble_3.1.0       lifecycle_1.0.0   
[21] crayon_1.4.1       purrr_0.3.4        vctrs_0.3.6        glue_1.4.2        
[25] proxy_0.4-25       compiler_4.0.3     pillar_1.5.1       generics_0.1.0    
[29] classInt_0.4-3     pkgconfig_2.0.3   
```

**Comment by bryanparthum** [comment] 2021-05-06 01:20
Hi all, same issue on my end (windows, too). The workaround `tolower()` doesn't seem to work in this case. Thanks!

```
library(tidyverse)
library(sf)
library(USAboundaries_0.3.1)
counties <- us_counties() 
colnames(counties) <- tolower(colnames(counties))
counties %>% rename(fips=geoid) 

Error in rename.sf(., fips = geoid) : internal error: can't find `agr` columns


sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1]   tidyverse_1.3.0      sf_0.9-6      USAboundaries_0.3.1

loaded via a namespace (and not attached):
 [1] httr_1.4.2              jsonlite_1.7.1          modelr_0.1.8            assertthat_0.2.1        sp_1.4-4                cellranger_1.1.0        yaml_2.2.1              ggrepel_0.8.2          
 [9] Rttf2pt1_1.3.8          pillar_1.4.7            backports_1.2.0         lattice_0.20-41         glue_1.4.2              extrafontdb_1.0         uuid_0.1-4              digest_0.6.27          
[17] rvest_0.3.6             colorspace_2.0-0        pkgconfig_2.0.3         broom_0.7.2             USAboundariesData_0.3.1 scales_1.1.1            tigris_1.0              proxy_0.4-25           
[25] generics_0.1.0          farver_2.0.3            ellipsis_0.3.1          withr_2.3.0             cli_2.2.0               crayon_1.3.4            maptools_1.0-2          fs_1.5.0               
[33] fansi_0.4.1             xml2_1.3.2              foreign_0.8-80          class_7.3-17            tools_4.0.3             hms_0.5.3               lifecycle_0.2.0         munsell_0.5.0          
[41] reprex_0.3.0            compiler_4.0.3          e1071_1.7-6             rlang_0.4.11            classInt_0.4-3          units_0.6-7             grid_4.0.3              rstudioapi_0.13        
[49] rappdirs_0.3.1          labeling_0.4.2          gtable_0.3.0            codetools_0.2-18        DBI_1.1.0               R6_2.5.0                lubridate_1.7.9.2       rgdal_1.5-18           
[57] utf8_1.1.4              extrafont_0.17          rprojroot_2.0.2         KernSmooth_2.23-18      stringi_1.5.3           parallel_4.0.3          Rcpp_1.0.6              vctrs_0.3.5            
[65] xfun_0.19               dbplyr_2.0.0            tidyselect_1.1.0       
```

**Comment by edzer** [comment] 2022-01-26 12:43
It looks like `us_counties()` gives a broken `sf` object; `st_sf()` can repair this, and
```r
map_sf <-  us_counties() |> st_sf() |>
  rename(State = state_name,
         County = name)
```
seems to work. I'll look into why this is the case.
